import { Shape, Size, Spacing, Typography } from '@/src/constants/design-tokens';
import { StyleSheet } from 'react-native';

export const routeAccountSelectorStyles = StyleSheet.create({
  container: {
    marginHorizontal: Spacing.lg,
    overflow: 'hidden',
  },
  routeStickyGroup: { width: '100%' },
  stickyRouteHeader: {
    marginHorizontal: Spacing.lg,
    padding: 1,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderTopLeftRadius: Shape.radius.lg,
    borderTopRightRadius: Shape.radius.lg,
  },
  stickyRouteDropdown: {
    marginHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    borderWidth: 1,
    borderTopWidth: 0,
    borderBottomLeftRadius: Shape.radius.lg,
    borderBottomRightRadius: Shape.radius.lg,
  },
  expandedWrapper: { borderRadius: Shape.radius.lg },
  dropdownLayer: {
    width: '100%',
    overflow: 'hidden',
  },
  dropdownCollapsed: {
    height: 0,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: Spacing.xs,
    width: '100%',
    zIndex: 2,
  },
  nodeWrapper: { flex: 1, minWidth: 0 },
  nodeButton: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    minHeight: Size.buttonLg,
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  standardNodeButton: { borderRadius: Shape.radius.lg, borderWidth: 1 },
  activeTabButton: {
    borderTopLeftRadius: Shape.radius.lg,
    borderTopRightRadius: Shape.radius.lg,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  nodeRoleLabel: {
    fontSize: Typography.sizes.xs,
    letterSpacing: Typography.letterSpacing.wide,
  },
  nodeAccountRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.xs,
    minWidth: 0,
  },
  nodeAccountText: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    fontSize: Typography.sizes.sm,
    lineHeight: Math.round(Typography.sizes.sm * Typography.lineHeights.tight),
  },
  nodePlaceholder: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    fontSize: Typography.sizes.sm,
    lineHeight: Math.round(Typography.sizes.sm * Typography.lineHeights.tight),
  },
  connectorContainer: { justifyContent: 'center', alignItems: 'center' },
  connectorArrow: {
    width: Size.md,
    height: Size.md,
    borderRadius: Shape.radius.full,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    alignItems: 'center',
  },
  connectorSwapButton: {
    width: Size.iconLg,
    height: Size.iconLg,
    borderRadius: Shape.radius.full,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownBody: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
  },
  utilityBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: Spacing.sm,
    marginBottom: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  utilityTitle: { fontSize: Typography.sizes.xs, letterSpacing: Typography.letterSpacing.wide },
  utilityActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  headerPlusButton: {
    width: Size.md,
    height: Size.md,
    borderRadius: Shape.radius.full,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearPillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Shape.radius.full,
    borderWidth: 1,
  },
  archivePillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Shape.radius.full,
    borderWidth: 1,
  },
  sectionBlock: { gap: Spacing.xs, paddingVertical: Spacing.none },
  sectionDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: Spacing.sm,
    marginTop: Spacing.none,
  },
  sectionToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.xs,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, minWidth: 0 },
  sectionTitleText: {
    fontSize: Typography.sizes.xs,
    letterSpacing: Typography.letterSpacing.normal,
  },
  sectionDot: { width: Spacing.sm, height: Spacing.sm, borderRadius: Shape.radius.xs },
  countBadge: {
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.none,
    borderRadius: Shape.radius.full,
    minWidth: Size.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countText: { fontSize: Typography.sizes.xs },
  compactPillGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    paddingTop: Spacing.none,
    paddingBottom: Spacing.xs,
  },
  emptyContainer: {
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.md,
    borderRadius: Shape.radius.md,
    borderWidth: 1,
    alignItems: 'center',
  },
});
