/**
 * App Configuration - Behavior defaults and app-wide settings
 * 
 * This file contains values that affect BEHAVIOR, not visual appearance.
 * Visual tokens belong in design-tokens.ts
 */

export const AppConfig = {
  // Default currency for new accounts
  defaultCurrency: 'USD' as const,

  // Default currency precision (decimal places)
  defaultCurrencyPrecision: 2,
  // Default locale for formatting
  defaultLocale: 'en-IN',

  // Versioning
  appVersion: '1.0.0',

  // Animation durations (in ms)
  animation: {
    fast: 200,
    normal: 300,
    slow: 500,
  },

  // Navigation and UI timing
  timing: {
    successDelay: 1000,  // Delay after success before navigation
    loadingDelay: 500,   // Minimum loading time
    debounceMs: 300,    // Input debounce timing
    focusDelayMs: 100,
    toastDurationMs: 3000,
    appLockGracePeriodMs: 2000,
    appLockAuthTransitionMs: 500,
  },

  // Input constraints
  input: {
    maxAccountNameLength: 100,
    maxDescriptionLength: 255,
    maxNotesLength: 500,
    maxDayOfMonthLength: 2,
    sms: {
      maxSenderMatchLength: 100,
      maxBodyMatchLength: 1000,
      maxStoredProcessedIds: 1000,
      previewBodyChars: 100,
    },
  },

  // Pagination
  pagination: {
    defaultPageSize: 20,
    dashboardPageSize: 50,
    maxPageSize: 100,
    budgetDetailsTransactionsPageSize: 1000,
    auditRecentLimit: 100,
    auditScreenLimit: 200,
    smsImportScanLimit: 50,
    smsImportSheetLimit: 200,
  },

  // Feature toggles
  features: {
    enableAnalytics: false,  // Analytics collection
    enableDebugMode: false,  // Debug logging
    enableExperimentalFeatures: false,
  },

  // Performance settings
  performance: {
    maxConcurrentOperations: 5,
    cacheTimeoutMs: 300000,  // 5 minutes
    rebuild: {
      checkpointInterval: 1000,
      batchSize: 500,
      queue: {
        debounceMs: 500,
        maxBatchSize: 50,
        retryLimit: 3,
        retryDelayMs: 2000,
      },
    },
  },

  // External API endpoints
  api: {
    exchangeRateBaseUrl: 'https://api.exchangerate-api.com/v4/latest',
  },

  // Business Logic Constants
  constants: {
    precision: 2,
    validation: {
      minAccountNameLength: 2,
      maxAccountNameLength: 100,
      maxTrimLength: 500,
      minDayOfMonth: 1,
      maxDayOfMonth: 31,
      minAprPercent: 0,
      maxAprPercent: 100,
    },
  },

  // System Account Configuration
  systemAccounts: {
    openingBalances: {
      namePrefix: 'Opening Balances',
      icon: 'scale',
      description: 'System account for initial balances',
    },
    balanceCorrections: {
      namePrefix: 'Balance Corrections',
      icon: 'construct',
      description: 'System account for balance corrections',
      legacyNames: ['Balance Corrections', 'Balance Correction', 'Balance Corrections ()'],
    },
  },

  // UI Strings
  strings: {
    common: {
      loading: 'Loading...',
      loadingMore: 'Loading more...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      alert: 'Alert',
      confirm: 'Confirm',
      ok: 'OK',
      noTransactions: 'No transactions',
      tryChangingFilters: 'Try changing your filters',
      allTime: 'All Time',
      searchPlaceholder: 'Search...',
    },
    dashboard: {
      emptyTitle: 'No transactions yet',
      emptySubtitle: 'Tap the + button to add your first transaction',
      recentTransactions: 'Recent Activity',
      searchResults: 'Search Results',
      greeting: (name: string) => `Hi, ${name || 'there'}!`,
      notificationsTitle: 'NOTIFICATIONS',
      safeToSpendTitle: 'SAFE TO SPEND',
      triggeringTransactionsTitle: 'TRIGGERING TRANSACTIONS',
      dismissedNotificationsTitle: 'Dismissed Notifications',
      noDismissedNotifications: 'No dismissed notifications found.',
      restore: 'Restore',
      manageDismissed: 'Manage',
      assets: 'Assets',
      debts: 'Unsettled Debts',
      budgets: 'Budgets',
      bills: 'Bills',
      shortfall: 'SHORTFALL',
      neededForObligations: 'Needed for obligations',
      afterObligations: 'After obligations',
      insightDetails: {
        title: 'Insight Details',
        emptyTitle: 'No transactions found',
        emptySubtitle: 'The transactions for this insight might have been deleted.',
        impact: 'Impact',
        whyThisAppeared: 'Why this appeared: ',
        recommendedAction: 'Recommended action',
        basisText: (days: number) => `Based on last ${days} days of activity`,
        severityLabel: {
          high: 'Action needed',
          medium: 'Watch',
          low: 'Info',
        },
      },
      noDataForBreakdown: 'Not enough liquid assets to determine breakdown.',
      safeToSpendExplanation: {
        title: 'How Safe to Spend Works',
        intro: 'Safe to Spend is your spendable limit after reserving money for known commitments.',
        unlocks: 'It helps you avoid accidental overspending by subtracting predictable obligations first.',
        formulaTitle: 'Formula:',
        formulaItems: [
          'Liquid Assets: Cash-like accounts available for near-term spending.',
          'Upcoming Income: Planned inflows from paychecks and transfers.',
          'Committed: 30-day forecasted outflows (Bills and Budgets).',
          'Unsettled Debts: Outstanding balances not yet covered by a planned payment.',
          'Safe to Spend: Your discretionary balance after all obligations.',
        ],
        bucketTitle: 'What each bucket includes:',
        exampleTitle: 'Current snapshot:',
        benefitsTitle: 'Why this is useful:',
        benefits: [
          'Reality-first planning: You spend from what remains after obligations, not gross balance.',
          'Built-in guardrails: Budget and bill commitments are treated as reserved funds.',
          'Transparent logic: You can always inspect the exact subtypes behind each bucket.',
        ],
        footer: 'If a bucket looks off, update account subtypes or budget scopes to improve the estimate.',
        closeCta: 'Got it',
      },
      legendDetails: {
        safeTitle: 'Safe to Spend',
        safeDesc: "This is your discretionary balance. It's the portion of your liquid assets remaining after reserving funds for all known 30-day obligations (bills, debt payments, and active budgets).",
        committedTitle: 'Committed Funds',
        committedDesc: 'These are funds reserved for upcoming planned payments (including credit card dues), journal transfers, and your active budget limits for the next 30 days.',
        debtsTitle: 'Total Debts',
        debtsDesc: 'This shows your total outstanding liability balance. Note that only the portion due within the next 30 days affects your Safe to Spend (and is already included in Committed Funds).',
        inflowTitle: 'Upcoming Inflows',
        inflowDesc: 'These are anticipated income journals or planned payment inflows expected within the next 30 days. They increase your future liquidity, enabling a higher Safe to Spend amount today.',
      },
      safeToSpendUi: {
        safePrefix: 'Safe:',
        committedPrefix: 'Committed:',
        debtsPrefix: 'Debts:',
        inflowPrefix: 'Inflows:',
        financiallySecure: 'Financially secure',
        assetsBucket: 'Assets bucket',
        debtsBucket: 'Unsettled Debts',
        debtsHint: 'Outstanding balances not yet covered by a planned payment.',
        debtsCallout: 'is already reserved in the "Committed" section above as you have a plan to settle it.',
        budgetsBucket: 'Budgets bucket',
        categoriesUsed: 'Categories used',
        accountsUsed: 'Accounts used',
        noneDetectedYet: 'None detected yet',
        projectedLiquidity: 'Projected Liquidity (Assets + Inflow):',
        committedLine: 'Committed (Budgets + Planned):',
        debtsLine: 'Unsettled Debts (Obligations without a plan):',
        safeToSpendLine: 'Safe to Spend:',
        calculationTitle: 'Calculation:',
        calculationFormula: 'min(Today\'s Assets, Trajectory Min)',
        plannedPayments: 'Planned Payments',
        plannedJournals: 'Planned Journals/Transfers',
        activeBudgets: 'Active Budgets (30-day proj.)',
        breakdownByAccount: 'Breakdown by Account',
        totalCommitted: 'Total Committed',
        creditCardStatements: 'Credit Card Statements',
        otherLiquidLiabilities: 'Other Liquid Liabilities',
        totalBalanceInfo: 'Total Balance (Informational)',
        upcomingIncome: 'Upcoming Income',
      },
      hub: {
        title: 'Hub',
        activeTab: 'Active',
        dismissedTab: 'Dismissed',
        unreadSmsTitle: (count: number) => `${count} Unprocessed ${count === 1 ? 'Message' : 'Messages'}`,
        unreadSmsSubtitle: "You have new SMS transactions that haven't been processed yet.",
        emptyState: "No active insights or notifications. You're all caught up!",
        noDismissed: 'No dismissed items.',
        restore: 'Restore',
        dismiss: 'Dismiss',
        emergencyFund: {
          title: 'Build an Emergency Fund',
          description: 'This insight appears because we did not detect a dedicated emergency-fund account in your assets.',
          highlight: 'A separate emergency fund makes your cash buffer visible and protects routine spending from surprise expenses.',
          fixTitle: 'How to fix it',
          step1: 'Create a new Asset account.',
          step2: 'Select the Emergency Fund subtype.',
          step3: 'Start with a small recurring transfer to build momentum.',
          actionClose: 'Got it',
          actionCreate: 'Create account',
          insight: {
            message: 'No Emergency Fund',
            description: "You don't have a dedicated account for emergencies.",
            suggestion: 'Consider creating an "Emergency Fund" asset account to track savings meant for unexpected expenses.',
          },
        },
        subscriptionAmnesia: {
          message: 'Subscription Amnesia',
          description: (amount: string, desc: string, acc: string) => `You have a recurring payment of ${amount} for "${desc}" in "${acc}".`,
          suggestion: 'Review this regular expense to see if it still provides value.',
        },
        spendingSpike: {
          message: 'Spending Spike',
          description: (subtype: string, percent: number) => `Spending on "${subtype}" is ${percent}% higher than your weekly average.`,
          suggestion: 'Check your recent activity in this category for any unusual spends.',
        },
      },
      notifications: {
        impact: 'Impact',
        whyThisAppeared: 'Why this appeared: ',
        basedOnLastDays: (days: number) => `Based on last ${days} days`,
        triggersCount: (count: number) => count === 1 ? '1 trigger' : `${count} triggers`,
        nextStep: 'Next step: ',
        planEmergencyFund: 'Plan emergency fund',
      },
    },
    journal: {
      emptyTitle: 'No transactions found',
      emptySubtitle: 'Try adjusting your search or date filter',
      transactions: 'Transactions',
      plannedPayments: 'Planned Payments',
      upcoming: 'Upcoming',
      searchResults: 'Search Results',
      more: (count: number) => `+${count} more`,
      from: 'From: ',
      to: 'To: ',
      transaction: 'Transaction',
      transfer: 'Transfer',
      transactionCount: (count: number) => count === 1 ? '1 transaction' : `${count} transactions`,
      reconciledUntilHere: 'Reconciled until here',
      reconciledUntilHereWithTime: (time: string) => `Reconciled until ${time}`,
      errors: {
        missingExchangeRate: (from: string, to: string) => `Missing exchange rate for ${from} to ${to}. Skipping amount from daily net total.`,
      },
    },
    reports: {
      title: 'Analytics',
      netWorthChange: 'NET WORTH CHANGE',
      totalIncome: 'TOTAL INCOME',
      totalExpense: 'TOTAL EXPENSE',
      incomeVsExpenseTrend: 'Income & Expense Trend',
      incomeBreakdown: 'Income Breakdown',
      spendingBreakdown: 'Spending Breakdown',
      noData: 'No expense data for this period.',
      showLess: 'Show Less',
      showAll: (count: number) => `Show All (${count})`,
    },
    settings: {
      title: 'Settings',
      sections: {
        personalization: 'Personalization',
        preferences: 'Preferences',
        communitySupport: 'Community & Support',
        general: 'General',
        appearance: 'Appearance',
        dataManagement: 'Data Management',
        maintenance: 'Maintenance',
        dangerZone: 'Danger Zone',
      },
      appearance: {
        themeTitle: 'Color Theme',
        themeDesc: 'Choose the color palette that suits your style.',
        typographyTitle: 'Typography',
        typographyDesc: 'Select the font family for headings and body text.',
        modeTitle: 'Mode',
        deepSpace: {
          label: 'Deep Space',
          desc: 'Dark blue tones, high contrast',
        },
        ivy: {
          label: 'Ivy',
          desc: 'Clean white, minimalist',
        },
        serifSans: {
          label: 'Serif & Sans',
          desc: 'DM Serif Display + Instrument Sans',
        },
        modernGeometric: {
          label: 'Modern Geometric',
          desc: 'Raleway everywhere',
        },
        customize: 'Customize',
        preview: 'Aa',
      },
      privacy: {
        title: 'Privacy Mode',
        description: 'Mask balances across the app',
        on: 'On',
        off: 'Off',
        widgetPrivacyTitle: 'Widget Privacy',
        widgetPrivacyDesc: 'Hide balances on home screen widgets',
      },
      advancedMode: {
        title: 'Advanced Mode',
        description: 'Default to multi-line entry and raw account selection.',
      },
      stats: {
        title: 'Account Statistics',
        description: 'Show monthly income/expense on cards',
      },
      data: {
        exportDesc: 'Create a backup of your data as a JSON file for backup or external use.',
        exportBtn: 'Create Backup',
        exportFilenameLabel: 'Backup Filename',
        exportFilenamePlaceholder: 'e.g., my-balance-backup',
        importBtn: 'Restore from Backup',
        auditDesc: 'View all changes made to your data for auditing and debugging.',
        auditBtn: 'View Audit Log',
      },
      maintenance: {
        integrityDesc: 'Verify and repair account balance inconsistencies if needed.',
        integrityBtn: 'Fix Integrity Issues',
        integrityTitle: 'Running Integrity Check',
        integrityWait: 'Please wait...',
        integrityHint: 'Do not close the app while this is running.',
      },
      danger: {
        cleanupDesc: 'Permanently delete soft-deleted records to free up space.',
        cleanupBtn: 'Cleanup Deleted Data',
        resetDesc: 'Wipe all data and reset the app to its original state.',
        resetBtn: 'Factory Reset',
      },
      version: (v: string) => `Balance v${v}`,
      personalization: {
        yourName: 'Your Name',
        yourNamePlaceholder: 'How should we call you?',
        themeTypographyTitle: 'Theme & Typography',
        themeTypographyDesc: 'Customize colors, fonts, and dark mode',
        smsAutoPostTitle: 'SMS Auto-Post Rules',
        smsAutoPostDesc: 'Manage rules to automatically post imported SMS',
      },
      community: {
        telegramTitle: 'Telegram Community',
        telegramDesc: 'Join our group for discussions and support',
        playStoreTitle: 'Rate on Play Store',
        playStoreDesc: 'Love the app? Leave a review',
        githubTitle: 'GitHub Source',
        githubDesc: 'Star the repo or contribute',
      },
      importTitle: 'Import Data',
      importIntro: 'Choose the format of your backup file to restore your data.',
      importNote: 'Note: Importing will replace all existing data on this device.',
      selectFile: (name: string) => `Select ${name} File`,
      currency: {
        title: 'Default Currency',
        description: 'Used for new accounts and total balance',
        selectTitle: 'Select Default Currency',
      },
      notifications: {
        title: 'Reminders',
        description: 'Get notified to add your transactions',
        cadenceLabel: 'Reminder Cadence',
        none: 'None',
        daily: 'Daily',
        weekly: 'Weekly',
        reminderTitle: 'Time to Balance your Books!',
        reminderBody: "Take a moment to add your recent transactions and keep your 'Safe to Spend' accurate.",
        testTitle: 'Test Reminder',
        testBody: 'This is a test notification from Balance.',
      },
    },
    transactionFlow: {
      amount: 'Amount',
      descriptionOptional: 'Description (Optional)',
      saving: 'Saving...',
      save: (type: string) => `Save ${type.toUpperCase()}`,
      chooseDifferentAccounts: 'Choose Different Accounts',
      fetchingRate: 'Fetching rate...',
      simple: 'Simple',
      advanced: 'Advanced',
      explanationIconAccessibility: 'What is Advanced Mode?',
      headers: {
        edit: 'Edit Transaction',
        new: 'New Transaction',
        default: 'Journal Entry',
      },
      banners: {
        editing: 'You are modifying an existing transaction',
      },
    },
    advancedModeExplanation: {
      title: 'What is Advanced Mode?',
      intro: 'Most finance apps force you into a "One-to-One" mindset: you spend $X at a store from one account. If you paid using two different cards, you’d have to log two separate transactions.',
      unlocks: 'Advanced Mode unlocks "Multi-leg Journals" (atomic splits). This allows you to group any number of items into a single, balanced entry.',
      exampleTitle: 'The Example:',
      exampleScenario: 'Imagine you buy a $50 meal, but you pay $40 from your Bank and $10 in Cash.',
      exampleItems: [
        'Bank — Credit $40 (Money leaving bank)',
        'Cash — Credit $10 (Money leaving wallet)',
        'Food — Debit $50 (Expense increased)',
      ],
      whyBetterTitle: 'Why it’s better:',
      benefits: [
        'Atomic Transactions: The entry only saves if it "Balances" (Sum of Debits = Sum of Credits). Your books stay perfectly accurate.',
        'Clean Ledger: You see one $50 meal in your reports, not two disconnected fragments.',
        'Power Features: It\'s perfect for split bills, paychecks (Income minus Taxes), or complex transfers where fees are involved.',
      ],
      footer: 'Simple Mode is just a shortcut we built on top of this engine to handle the boring 90% of daily expenses, but Advanced is where the real power of the app\'s double-entry engine lives.',
    },
    accounts: {
      types: {
        asset: 'Asset',
        liability: 'Liability',
        equity: 'Equity',
        income: 'Income',
        expense: 'Expense',
      },
      selectCurrency: 'Select Currency',
      form: {
        accountName: 'Account Name',
        accountNamePlaceholder: 'e.g., Checking Account',
        accountType: 'Account Type',
        accountSubtype: 'Account Subtype',
        currentBalance: 'Current Balance',
        initialBalance: 'Initial Balance',
        balancePlaceholder: '0.00',
        parentAccount: 'Parent Account (Optional)',
        clear: 'Clear',
      },
      hierarchy: {
        title: 'Manage Hierarchy',
        description: 'Select an account to move it, or create a new parent organizational account.',
        newParentButton: 'New Parent Account',
        addChild: 'Add child account...',
        modalTitle: 'Hierarchy Builder',
        modalDescription: (accountName: string) => `Configure structure for "${accountName}"`,
        addChildrenLabel: 'ADD AVAILABLE ACCOUNTS AS CHILDREN:',
        moveParentLabel: 'MOVE UNDER ANOTHER PARENT:',
        hasTransactions: 'Has Transactions',
      },
      reconciliation: {
        reconciledLabel: (date: string) => `RECONCILED: ${date}`,
        alert: {
          title: 'Reconcile Account',
          message: 'Mark this account as reconciled until now?',
          successTitle: 'Reconciled',
          successMessage: 'Account has been marked as reconciled.',
        },
      },
    },
    advancedEntry: {
      createTitle: 'Create Journal Entry',
      editTitle: 'Edit Journal Entry',
      dateTime: 'Date & Time',
      description: 'Description',
      descriptionPlaceholder: 'Enter description',
      journalLines: 'Journal Lines',
      addLine: '+ Add Line',
      addLineAccessibility: 'Add line',
      lineTitle: (index: number) => `Line ${index}`,
      removeLine: 'Remove',
      selectAccount: 'Select Account',
      type: 'Type',
      debit: 'Debit',
      credit: 'Credit',
      amountPlaceholder: '0.00',
      notes: 'Notes',
      notesPlaceholder: 'Optional notes',
      exchangeRate: 'Exchange Rate (Optional)',
      autoFetch: 'Auto-fetch',
      ratePlaceholder: 'e.g., 1.1050',
      rateHelpSame: 'Not needed (same as base currency)',
      rateHelpConvert: (from: string, to: string) => `Rate to convert ${from} to ${to}`,
      updating: 'Updating...',
      creating: 'Creating...',
      updateJournal: 'Update Journal',
      createJournal: 'Create Journal',
      editing: 'EDITING',
    },
    onboarding: {
      iconPickerTitle: 'Select Icon',
      splash: {
        title: 'Find Your\nPhantom Surplus',
        subtitle: "Stop wondering where it went.\nStart seeing where it's stays.",
        inputLabel: 'What should we call you?',
        inputPlaceholder: 'Enter your name',
        btnGetStarted: 'Get Started',
        dividerOr: 'OR',
        btnRestore: 'Restore Backup',
      },
      currency: {
        title: 'Default Currency',
        subtitle: 'Select your primary currency. You can add more later.',
        searchPlaceholder: 'Search currency...',
      },
      accounts: {
        title: 'Setup Accounts',
        subtitle: 'Where is your money? Select all that apply.',
        placeholder: 'Add custom account...',
      },
      categories: {
        title: 'Setup Categories',
        subtitle: 'Select categories you use often.',
        placeholder: 'Add category...',
        typeLabels: { income: 'Income', expense: 'Expense' },
      },
      finalize: {
        title: 'The Blueprint is Ready',
        subtitle: "We'll show you your 'Safe to Spend' limit every morning. No more guessing, no more guilt.",
        btnFinish: "Uncover Notifications",
      },
    },
    journalSummary: {
      title: 'Summary',
      totalDebits: 'Total Debits:',
      totalCredits: 'Total Credits:',
      balance: 'Balance:',
      balanced: (curr: string) => `✓ Journal is balanced in ${curr}`,
      unbalanced: (curr: string) => `✗ Journal must be balanced in ${curr}`,
    },
    validation: {
      accountNameRequired: 'Account name is required',
      accountNameTooShort: (min: number) => `Account name must be at least ${min} characters`,
      accountNameTooLong: (max: number) => `Account name must be less than ${max} characters`,
      invalidCharacters: 'Account name contains invalid characters',
      simpleModeTooManyLines: 'Cannot switch to Simple mode with more than 2 transaction lines.',
    },
    audit: {
      logTitle: 'Audit Log',
      editHistory: 'Edit History',
      emptyLogs: 'No audit logs found',
      viewDetails: 'View details',
      idLabel: (id: string) => `ID: ${id}`,
      typeChanged: '(type changed)',
      transactionsLabel: 'transactions:',
      tables: ['journals', 'transactions', 'accounts'],
      errors: {
        notFound: (id: string) => `Entity ${id} not found`,
        loadFailed: 'Failed to load audit logs',
      },
    },
    formats: {
      date: 'YYYY-MM-DD',
    },
    maintenance: {
      importSuccess: 'Import Successful',
      resetComplete: 'Factory Reset Complete',
      importDesc: 'Your data has been successfully imported into the local database.',
      resetDesc: 'All data, accounts, and settings have been permanently erased.',
      stats: {
        accounts: 'Accounts',
        journals: 'Journals',
        transactions: 'Transactions',
        budgets: 'Budgets',
        auditLogs: 'Audit Logs',
        skippedItems: 'Skipped Items',
      },
      restartNote: 'A restart is required to finalize changes and re-initialize the application engine.',
      restartBtn: 'Restart App',
    },
    plannedPayments: {
      title: 'Planned Payments',
      details: {
        deleteConfirmTitle: 'Delete Planned Payment?',
        deleteConfirmMessage: 'Are you sure you want to delete this planned payment?',
        postNowTitle: 'Post Transaction Now?',
        skipTitle: 'Skip Occurrence?',
        skipConfirm: 'Skip',
      },
      emptyTitle: 'No Planned Payments',
      emptySubtitle: 'Create your first recurring payment rule to automate your tracking.',
      nameLabel: 'Rule Name',
      namePlaceholder: 'e.g., Monthly Rent',
      amountLabel: 'Amount',
      amountPlaceholder: '0.00',
      fromAccountLabel: 'From Account',
      toAccountLabel: 'To Account',
      selectAccount: 'Select Account',
      recurrenceTitle: 'Recurrence',
      intervalLabel: 'Interval',
      autoPostLabel: 'Auto-Post',
      saveLabel: 'Save Rule',
      savingLabel: 'Saving...',
      nextOccurrence: (date: string) => `Next: ${date}`,
      everyDay: 'Every day',
      everyWeek: 'Every week',
      everyMonth: 'Every month',
      everyYear: 'Every year',
      everyN: (n: number, type: string) => `Every ${n} ${type}s`,
      statusPaused: 'PAUSED',
      formTitleNew: 'New Recurring Rule',
      formTitleEdit: 'Edit Recurring Rule',
      dayOfWeek: 'Day of Week',
      dayOfMonth: 'Day of Month (1-31)',
      month: 'Month',
      selectMonth: 'Select Month',
      monthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    },
    budget: {
      details: {
        deleteTitle: 'Delete Budget',
        deleteConfirm: 'Are you sure you want to delete this budget?',
      },
    },
    alerts: {
      success: 'Success',
      error: 'Error',
      warning: 'Warning',
      info: 'Info',
      validationError: 'Validation Error',
      databaseError: 'Database Error',
      connectionError: 'Connection Error',
      genericError: 'Something went wrong. Please try again.',
      databaseErrorMessage: 'There was a problem saving your data. Please try again.',
      networkErrorMessage: 'Please check your internet connection and try again.',
    },
  },

  // Layout Constants
  layout: {
    maxContentWidth: 400,
    popupModalMaxWidth: 460,
    popupModalHeightPercent: 84,
    safeToSpendChartHeight: 150,
    listEstimatedItemSize: 120,
    compactListEstimatedItemSize: 100,
    modalHeightPercent: '70%',
    hierarchyModalHeightPercent: '80%',
    iconCircleSize: 32, // Match Size.iconLg or similar
    finalizeIconSize: 84, // Size.xxl * 2 or similar
    finalizeSubtitleMaxWidth: 300,
    toastTopOffset: 60,
  },

  // Default Values
  defaults: {
    reportDays: 30,
    safeToSpendDays: 30,
    chartTickCount: 5,
    safeToSpendDaysCap: 99,
    reportMonthlyBucketThresholdDays: 60,
    journalPageSize: 50,
    insightDetailsFetchLimit: 100,
    plannedJournalLimit: 10,
  },
  // Insight Configuration
  insights: {
    lookbackDays: 90,
    refreshIntervalMs: 60 * 60 * 1000,
    observeDebounceMs: 250,
    patternDebounceMs: 500,
    minRecurringIntervalDays: 25,
    maxRecurringIntervalDays: 35,
    minAnnualRecurringIntervalDays: 360,
    maxAnnualRecurringIntervalDays: 370,
    minRecurringCount: 3,
    spendingSpikeMultiplier: 1.5,
    spendingSpikeSeverityThreshold: 1000,
    spikeWindowDays: 7,
    recurringHorizonDays: 25,
    maxPlannedPaymentGenerations: 365,
    liabilityDefaultDueDay: 20,
    liabilityFallbackDeductionDay: 28,
    liabilityErrorFallbackOffsetDays: 15,
  },
  dateTimePicker: {
    hoursInDay: 24,
    minutesInHour: 60,
    columnHeight: 150,
    containerHeight: 180,
    labelHeight: 30,
    scrollSnapDelayMs: 100,
  },
  toast: {
    animationDurationMs: 200,
    enterOffsetY: 20,
  },
  time: {
    msPerMinute: 60 * 1000,
    msPerHour: 60 * 60 * 1000,
    msPerDay: 24 * 60 * 60 * 1000,
    daysPerWeek: 7,
  },
} as const
