/**
 * Currency Definitions
 * 
 * Shared source of truth for currency metadata (symbols, names, precision).
 * Used by initialization services and formatters.
 */

export interface CurrencyData {
    code: string
    symbol: string
    name: string
    precision: number
}

export const COMMON_CURRENCIES: CurrencyData[] = [
    { code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham', precision: 2 },
    { code: 'AFN', symbol: 'Af', name: 'Afghan Afghani', precision: 0 },
    { code: 'ALL', symbol: 'L', name: 'Albanian Lek', precision: 2 },
    { code: 'AMD', symbol: '֏', name: 'Armenian Dram', precision: 2 },
    { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', precision: 2 },
    { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', precision: 2 },
    { code: 'ARS', symbol: '$', name: 'Argentine Peso', precision: 2 },
    { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', precision: 2 },
    { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', precision: 2 },
    { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', precision: 2 },
    { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', precision: 2 },
    { code: 'BBD', symbol: '$', name: 'Barbadian Dollar', precision: 2 },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', precision: 2 },
    { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', precision: 2 },
    { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', precision: 3 },
    { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', precision: 0 },
    { code: 'BMD', symbol: '$', name: 'Bermudan Dollar', precision: 2 },
    { code: 'BND', symbol: '$', name: 'Brunei Dollar', precision: 2 },
    { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', precision: 2 },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', precision: 2 },
    { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', precision: 2 },
    { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', precision: 2 },
    { code: 'BWP', symbol: 'P', name: 'Botswanan Pula', precision: 2 },
    { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', precision: 2 },
    { code: 'BZD', symbol: '$', name: 'Belize Dollar', precision: 2 },
    { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', precision: 2 },
    { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', precision: 2 },
    { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', precision: 2 },
    { code: 'CLF', symbol: 'UF', name: 'Chilean Unit of Account (UF)', precision: 4 },
    { code: 'CLP', symbol: '$', name: 'Chilean Peso', precision: 0 },
    { code: 'CNH', symbol: '¥', name: 'Chinese Yuan (Offshore)', precision: 2 },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', precision: 2 },
    { code: 'COP', symbol: '$', name: 'Colombian Peso', precision: 0 },
    { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', precision: 2 },
    { code: 'CUC', symbol: '$', name: 'Cuban Convertible Peso', precision: 2 },
    { code: 'CUP', symbol: '₱', name: 'Cuban Peso', precision: 2 },
    { code: 'CVE', symbol: '$', name: 'Cabo Verde Escudo', precision: 2 },
    { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', precision: 2 },
    { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', precision: 0 },
    { code: 'DKK', symbol: 'kr', name: 'Danish Krone', precision: 2 },
    { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', precision: 2 },
    { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', precision: 2 },
    { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', precision: 2 },
    { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', precision: 2 },
    { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', precision: 2 },
    { code: 'EUR', symbol: '€', name: 'Euro', precision: 2 },
    { code: 'FJD', symbol: '$', name: 'Fijian Dollar', precision: 2 },
    { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', precision: 2 },
    { code: 'GBP', symbol: '£', name: 'British Pound', precision: 2 },
    { code: 'GEL', symbol: '₾', name: 'Georgian Lari', precision: 2 },
    { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', precision: 2 },
    { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', precision: 2 },
    { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', precision: 2 },
    { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', precision: 0 },
    { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', precision: 2 },
    { code: 'GYD', symbol: '$', name: 'Guyanese Dollar', precision: 2 },
    { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', precision: 2 },
    { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', precision: 2 },
    { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', precision: 2 },
    { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', precision: 2 },
    { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', precision: 2 },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', precision: 2 },
    { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', precision: 2 },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', precision: 2 },
    { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', precision: 3 },
    { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', precision: 2 },
    { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', precision: 0 },
    { code: 'JMD', symbol: '$', name: 'Jamaican Dollar', precision: 2 },
    { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', precision: 3 },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen', precision: 0 },
    { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', precision: 2 },
    { code: 'KGS', symbol: 'с', name: 'Kyrgystani Som', precision: 2 },
    { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', precision: 2 },
    { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', precision: 0 },
    { code: 'KPW', symbol: '₩', name: 'North Korean Won', precision: 2 },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won', precision: 0 },
    { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', precision: 3 },
    { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar', precision: 2 },
    { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', precision: 2 },
    { code: 'LAK', symbol: '₭', name: 'Laotian Kip', precision: 2 },
    { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', precision: 2 },
    { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', precision: 2 },
    { code: 'LRD', symbol: '$', name: 'Liberian Dollar', precision: 2 },
    { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', precision: 2 },
    { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', precision: 3 },
    { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', precision: 2 },
    { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', precision: 2 },
    { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', precision: 2 },
    { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', precision: 2 },
    { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', precision: 2 },
    { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', precision: 2 },
    { code: 'MOP', symbol: 'P', name: 'Macanese Pataca', precision: 2 },
    { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', precision: 2 },
    { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', precision: 2 },
    { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', precision: 2 },
    { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', precision: 2 },
    { code: 'MXN', symbol: '$', name: 'Mexican Peso', precision: 2 },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', precision: 2 },
    { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', precision: 2 },
    { code: 'NAD', symbol: '$', name: 'Namibian Dollar', precision: 2 },
    { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', precision: 2 },
    { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', precision: 2 },
    { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', precision: 2 },
    { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', precision: 2 },
    { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', precision: 2 },
    { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', precision: 3 },
    { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', precision: 2 },
    { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', precision: 2 },
    { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', precision: 2 },
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso', precision: 2 },
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', precision: 2 },
    { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', precision: 2 },
    { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', precision: 0 },
    { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Rial', precision: 2 },
    { code: 'RON', symbol: 'lei', name: 'Romanian Leu', precision: 2 },
    { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', precision: 2 },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble', precision: 2 },
    { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', precision: 0 },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', precision: 2 },
    { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar', precision: 2 },
    { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', precision: 2 },
    { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', precision: 2 },
    { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', precision: 2 },
    { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', precision: 2 },
    { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', precision: 2 },
    { code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone (new)', precision: 2 },
    { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', precision: 2 },
    { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', precision: 2 },
    { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', precision: 2 },
    { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', precision: 2 },
    { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', precision: 2 },
    { code: 'SYP', symbol: '£', name: 'Syrian Pound', precision: 2 },
    { code: 'SZL', symbol: 'L', name: 'Eswatini Lilangeni', precision: 2 },
    { code: 'THB', symbol: '฿', name: 'Thai Baht', precision: 2 },
    { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', precision: 2 },
    { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', precision: 2 },
    { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', precision: 3 },
    { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', precision: 2 },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira', precision: 2 },
    { code: 'TTD', symbol: '$', name: 'Trinidad and Tobago Dollar', precision: 2 },
    { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', precision: 2 },
    { code: 'TZS', symbol: 'Sh', name: 'Tanzanian Shilling', precision: 2 },
    { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', precision: 2 },
    { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', precision: 0 },
    { code: 'USD', symbol: '$', name: 'US Dollar', precision: 2 },
    { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', precision: 2 },
    { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som', precision: 2 },
    { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar Soberano', precision: 2 },
    { code: 'VND', symbol: '₫', name: 'Vietnamese Đồng', precision: 0 },
    { code: 'VUV', symbol: 'Vt', name: 'Vanuatu Vatu', precision: 0 },
    { code: 'WST', symbol: 'T', name: 'Samoan Tala', precision: 2 },
    { code: 'XAF', symbol: 'FCFA', name: 'CFA Franc BEAC', precision: 0 },
    { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar', precision: 2 },
    { code: 'XOF', symbol: 'CFA', name: 'CFA Franc BCEAO', precision: 0 },
    { code: 'XPF', symbol: '₣', name: 'CFP Franc', precision: 0 },
    { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', precision: 2 },
    { code: 'ZAR', symbol: 'R', name: 'South African Rand', precision: 2 },
    { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', precision: 2 },
    { code: 'ZWL', symbol: '$', name: 'Zimbabwean Dollar', precision: 2 },
]

export const CURRENCY_SYMBOLS: Record<string, string> = COMMON_CURRENCIES.reduce((acc, curr) => {
    acc[curr.code] = curr.symbol
    return acc
}, {} as Record<string, string>)

export const CURRENCY_PRECISIONS: Record<string, number> = COMMON_CURRENCIES.reduce((acc, curr) => {
    acc[curr.code] = curr.precision
    return acc
}, {} as Record<string, number>)
