export const budgetDetailRedesignStrings = {
  loading: 'Loading budget…',
  missingTitle: 'Budget not found',
  missingSubtitle: 'This budget may have been deleted.',
  goBack: 'Go back',
  leftToSpend: 'Left to spend',
  spent: 'Spent',
  limit: 'of',
  pastLimit: 'past',
  overTheLimit: 'Over the limit',
  overBy: (percent: number | string) => `By ${percent}%`,
  spentPercent: (percent: number | string) => `${percent}% spent`,
  incomplete: 'Incomplete',
  nothingSpent: 'Nothing spent yet',
  perDayLeft: 'Per day left',
  days: 'Days',
  sameDay: (period: string) => `${period}, same day`,
  total: (period: string) => `${period} total`,
  overPace: 'over pace',
  underPace: 'under pace',
  spendingSoFar: 'Spending so far',
  today: 'Today',
  evenPace: 'Even pace',
  whereItWent: 'Where it went',
  unavailableCategory: 'Unavailable category',
  showCategoryActivity: (name: string) => `Show ${name} activity`,
  deselectCategoryActivity: (name: string) => `Clear ${name} activity filter`,
  entries: (count: number) => `${count} ${count === 1 ? 'entry' : 'entries'}`,
  refundsAndReversals: 'Refunds and reversals',
  retryBreakdown: 'Retry breakdown',
  noCategorySpending: 'No category spending in this period.',
  incompleteCurrencyValuation: 'Incomplete currency valuation',
  partialCategoryAmounts: 'Some entries could not be converted. Category amounts are partial.',
  setup: 'Setup',
  setupSummary: (period: string, accounts: string) => `${period} · from ${accounts}`,
  loadingAccounts: 'Loading accounts…',
  noFundingAccounts: 'Automatic account selection',
  selectedAccountsUnavailable: 'Selected accounts are unavailable',
  activity: 'Activity',
  allActivityCount: (count: number) => `All ${count}`,
  categoryActivityCount: (name: string, count: number) => `${name} · ${count} ×`,
  clearActivityFilter: 'Clear category activity filter',
  previousPeriod: 'Previous period',
  chartAccessibilityLabel: (status: string, amount: string, elapsed: number) =>
    `${status}, ${amount}, ${elapsed}% of period elapsed`,
  status: {
    onPace: 'On pace',
    aheadOfPace: 'Ahead of pace',
    nearLimit: 'Near limit',
    over: 'Over',
    incomplete: 'Incomplete',
  },
  periodAccessibility: (label: string, range: string, daysLeft?: number) =>
    `${label}, ${range}${daysLeft === undefined ? '' : `, ${daysLeftLabel(daysLeft)}`}`,
  daysLeft: (count: number) => `${count} ${count === 1 ? 'day' : 'days'} left`,
  previousPeriodButton: 'Previous period',
  nextPeriodButton: 'Next period',
  backToToday: 'Back to today',
  chartStartDate: (date: string) => date,
  chartEndDate: (limit: string, date: string) => `Limit ${limit} · ${date}`,
  missingFxEntries: (count: number, currencyCode: string) =>
    `${count} ${currencyCode} ${count === 1 ? 'entry' : 'entries'} without a rate · tap to fix`,
} as const;

function daysLeftLabel(count: number) {
  return `${count} ${count === 1 ? 'day' : 'days'} left`;
}
