export const budgetFormStrings = {
  namePlaceholder: 'Name, like “Eating out”',
  whatCounts: 'What counts',
  whatCountsHint: 'Spending in these categories uses up the budget.',
  addCategory: 'Add',
  addCategories: 'Add categories',
  removeCategory: (name: string) => `Remove ${name}`,
  allCategories: 'All categories',
  historyTitle: 'Spending history',
  historyAverage: (average: string) => `avg ${average}`,
  historyLimit: (limit: string) => `Dashed line: ${limit} limit`,
  historyStart: (label: string) => label,
  historyCurrent: (label: string) => `${label} so far`,
  historyAccessibility: (summary: string) => `Spending history. ${summary}`,
  yourAverage: (average: string) => `Your average is ${average}`,
  useAverage: 'Use it',
  settings: 'Settings',
  resets: 'Resets',
  setAsideFrom: 'Set aside from',
  setAsideSubtitle: 'Safe to Spend holds this amount back from these accounts',
  automaticAccount: 'Automatic',
  chipAccessibility: (name: string) => `${name} category`,
  intervalUnits: {
    day: 'day',
    week: 'week',
    month: 'month',
    year: 'year',
  },
  limitEach: (unit: string) => `Limit each ${unit}`,
  limitEvery: (count: number, unit: string) =>
    `Limit every ${count} ${unit}${count === 1 ? '' : 's'}`,
} as const;
