export const commitmentsRedesignStrings = {
  title: 'Commitments',
  budgets: 'Budgets',
  thisMonth: 'This month',
  planned: 'Planned',
  budgetAction: 'Budget',
  plannedAction: 'Planned',
  expenseAction: 'Expense',
  createBudget: 'Create a budget',
  createPlanned: 'Create a planned payment',
  addExpense: 'Add an expense',
  menuTitle: 'Actions',
  moreActions: 'More actions',
  closeMenu: 'Close actions',
  edit: 'Edit',
  delete: 'Delete',
  pause: 'Pause schedule',
  resume: 'Resume schedule',
  openPending: 'Open pending entry',
  monthlyBudgets: 'Monthly budgets',
  attentionFirst: 'Needs attention first',
  budgetsLoadError: 'We could not load budgets.',
  nothingSpent: 'nothing spent yet',
  unavailableCategory: 'Unavailable category',
  opensBudget: 'Opens budget details',
  left: (money: string) => `${money} left`,
  over: (money: string) => `${money} over`,
  ofLimit: (money: string) => `of ${money}`,
  overOfLimit: (money: string) => `over the ${money} limit`,
  leftOfLimit: (money: string) => `left of ${money} limit`,
  spent: (money: string) => `${money} spent`,
  daily: (status: string, money: string) => `${status} · ${money}/day`,
  overPercent: (percent: string) => `Over by ${percent}`,
  otherCurrencies: (count: number) => `+ ${count} in other currencies`,
  otherCadences: (count: number) => `${count} with other periods`,
  overCount: (count: number) => `${count} over`,
  daysLeft: (count: number) => `${count} days left`,
  period: (name: string, days: number) => `${name} · ${days} days left`,
  todayMarker: (day: number, total: number) => `Today, day ${day} of ${total}`,
  paceAccessibility: (status: string, spent: string, elapsed: string) =>
    `${status}, ${spent} spent, ${elapsed} of period elapsed`,
  progressAccessibility: (spent: string) => `${spent} of budget spent`,
  missingFx: (count: number, currencies: string) =>
    `${count} ${currencies ? `${currencies} ` : ''}${count === 1 ? 'entry' : 'entries'} without a rate`,
  fixFx: (message: string) => `${message} · tap to fix`,
  categorySummary: (names: string) => `Categories: ${names}`,
  remainingAccessibility: (
    name: string,
    amount: string,
    spent: string,
    limit: string,
    status: string,
  ) => `${name}. ${amount}. ${spent}. ${limit}. ${status}`,
};
