export const formPrimitivesStrings = {
  schedule: 'Schedule',
  scheduleSheetTitle: 'Repeats',
  repeats: 'Repeats',
  resets: 'Resets',
  every: 'Every',
  editSchedule: (sentence: string) => `${sentence}, edit schedule`,
  day: 'Day',
  week: 'Week',
  month: 'Month',
  year: 'Year',
  everyPrefix: (count: number) => (count === 1 ? 'Every ' : `Every ${count} `),
  dayUnit: 'day',
  weekUnit: 'week',
  monthUnit: 'month',
  yearUnit: 'year',
  on: ' on ',
  onThe: ' on the ',
  yearIn: ' in ',
  ordinal: (day: number) => {
    const lastTwo = day % 100;
    const suffix =
      lastTwo >= 11 && lastTwo <= 13
        ? 'th'
        : (({ 1: 'st', 2: 'nd', 3: 'rd' } as Record<number, string>)[day % 10] ?? 'th');
    return `${day}${suffix}`;
  },
  weekdayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  weekdayShortNames: ['Su', 'M', 'Tu', 'W', 'Th', 'F', 'Sa'],
  monthShortNames: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  onDay: 'On day',
  inMonth: 'In month',
  decreaseRepeatCount: 'Decrease repeat count',
  increaseRepeatCount: 'Increase repeat count',
  editRepeatCount: 'Repeat interval',
  next: 'Next ',
  closeDialog: 'Close dialog',
  doneAccessibility: 'Done',
  accountKind: 'Account kind',
  nextItem: 'Next',
  previousItem: 'Previous',
  clearValue: (title: string) => `Clear ${title}`,
  formRowAccessibility: (
    title: string,
    subtitle?: string,
    value?: string | null,
    placeholder?: string,
  ) => [title, subtitle, value || placeholder].filter(Boolean).join(', '),
  currencyAccessibility: (code: string) => `Currency ${code}`,
  allKindsAccessibility: 'All kinds',
  dismissSuggestion: 'Dismiss suggestion',
  dayOfMonth: (day: number) => `Day ${day}`,
  lastDayOfMonth: 'Last day of month',
  daysSection: 'On day',
  monthsSection: 'In month',
  repeatCountError: 'Enter a whole number from 1 to 9999.',
  lastDay: 'Last day',
  lastDaySentence: 'last day',
  done: 'Done',
  invalidRepeatCount: 'Enter a whole number from 1 to 9999.',
} as const;
