export const journalDetailsStrings = {
  title: 'Journal details',
  edit: 'Edit journal',
  duplicate: 'Duplicate',
  delete: 'Delete journal',
  missing: 'Transaction not found',
  back: 'Go Back',
  noDescription: 'No description',
  unknownAccount: 'Unknown Account',
  statuses: {
    DRAFT: 'Draft',
    POSTED: 'Posted',
    REVERSED: 'Reversed',
    PLANNED: 'Planned',
    SKIPPED: 'Skipped',
    PAUSED: 'Paused',
  },
  displayTypes: {
    INCOME: 'Income',
    EXPENSE: 'Expense',
    TRANSFER: 'Transfer',
    MIXED: 'Mixed',
  },
  accountTypes: {
    ASSET: 'Asset',
    LIABILITY: 'Liability',
    EQUITY: 'Equity',
    INCOME: 'Income',
    EXPENSE: 'Expense',
  },
  accounts: (count: number) => `${count} accounts`,
  openAccount: (name: string) => `Open ${name}`,
  entries: (count: number) => `${count} entries`,
  due: (date: string, relative: string) => `Due ${date} · ${relative}`,
  dueToday: 'today',
  inDays: (days: number) => `in ${days} day${days === 1 ? '' : 's'}`,
  overdue: (days: number) => `${days} day${days === 1 ? '' : 's'} overdue`,
  afterJournal: 'After this journal',
  balanced: 'Balanced',
  balancedIn: (currency: string) => `Balanced in ${currency}`,
  balancedMark: (label: string) => `✓ ${label}`,
  balance: 'Balance',
  owed: 'Owed',
  after: (amount: string) => `${amount} after`,
  owedAfter: (amount: string) => `${amount} owed after`,
  from: 'From',
  to: 'To',
  credits: 'Credits',
  debits: 'Debits',
  totalUnavailable: 'Total unavailable',
  valueUnavailable: 'Value unavailable',
  balanceUnavailable: 'Balance unavailable',
  plannedOut: (amount: string, account: string) =>
    `Not posted yet. Posting moves ${amount} out of ${account}.`,
  plannedIn: (amount: string, account: string) =>
    `Not posted yet. Posting moves ${amount} into ${account}.`,
  plannedSplit: 'Not posted yet. Posting applies the entries below.',
  post: 'Post now',
  skip: 'Skip this one',
  accounting: 'Accounting',
  unbalanced: 'Unbalanced',
  needsReview: 'Needs review',
  difference: 'Difference',
  unavailable: 'Unavailable',
  budget: 'Budget',
  left: (remaining: string, amount: string) => `${remaining} left of ${amount}`,
  over: (over: string, amount: string) => `${over} over ${amount}`,
  incompleteBudget: 'Remaining unavailable · some entries could not be valued',
  more: (count: number) => `+${count} more`,
  schedule: 'Schedule',
  occurrence: 'Occurrence',
  since: (date: string) => `Since ${date}`,
  afterThis: 'After this',
  noNextOccurrence: 'No further occurrence',
  autoPost: 'auto-post',
  manualPost: 'manual post',
  revertScheduled: 'Revert to scheduled',
  source: 'Source',
  smsFrom: (sender: string) => `SMS from ${sender}`,
  unknownSender: 'unknown sender',
  autoPosted: 'Auto-posted',
  imported: 'Imported',
  importedFrom: (source: string) => `Imported from ${source}`,
  importSources: {
    sms: 'SMS',
    ivy_import: 'Ivy Wallet',
    manual: 'Manual',
    manual_post: 'Manual',
    planned_payment: 'Scheduled',
  },
  ref: (reference: string) => `Ref ${reference}`,
  received: (date: string, method: string) => `Received ${date} · ${method}`,
  linkedManually: 'linked manually',
  amountRead: 'Amount read',
  accountHint: 'Account hint',
  merchant: 'Merchant',
  reference: 'Reference',
  legendMark: (label: string) => `● ${label}`,
  inbox: 'Open in SMS inbox',
  hiddenSms: 'Message hidden in privacy mode',
  closeSms: 'Close message',
  history: 'History',
  fullLog: 'Full log',
  revert: 'Revert this change',
  revertMark: '↶',
  changeArrow: ' → ',
  flow: (from: string, to: string) => `${from} → ${to}`,
  revertChange: (field: string, from: string, to: string) => `${field} (${from} → ${to})`,
  revertTitle: 'Revert this change?',
  revertSummary: (summary: string) => `${summary} will go back to the previous values.`,
  revertFallback: 'This change will be undone. Continue?',
  created: 'Created',
  updated: 'Last updated',
  historyUnavailable: 'History unavailable',
  budgetsUnavailable: 'Budget usage unavailable',
  sourceUnavailable: 'Import details unavailable',
  retry: 'Try again',
  record: 'Record',
  journalNumber: 'Journal no.',
  copied: 'Journal ID copied',
  copyFailed: 'Could not copy the journal ID',
  field: {
    description: 'Description',
    notes: 'Note',
    totalAmount: 'Amount',
    amount: 'Amount',
    journalDate: 'Date',
    status: 'Status',
    currencyCode: 'Currency',
    category: 'Category',
    account: 'Account',
    transactions: 'Entries',
    exchangeRate: 'Exchange rate',
  },
  events: {
    'journal.created': 'Created',
    'journal.sms_auto_posted': 'Auto-posted from SMS',
    'journal.imported': 'Imported',
    'journal.updated': 'Edited',
    'journal.renamed': 'Edited',
    'journal.accounts_retargeted': 'Edited',
    'journal.posted': 'Posted',
    'journal.planned_payment_skipped': 'Skipped',
    'journal.reverted_to_planned': 'Moved back to scheduled',
    'journal.status_changed': 'Status changed',
    'journal.reversed': 'Reversed',
    'journal.reversal_created': 'Reversal of…',
    'journal.reverted': 'Change reverted',
    'transaction_inbox_record.linked': 'SMS received',
  },
};
