export const ONBOARDING_STRINGS = {
  brand: 'full frills balance',
  welcomeTagline: 'A calmer way to track money.',
  welcomeBody: 'See what you can safely spend after the money and payments you already know about.',
  startWithMoney: 'Start with my money',
  restoreBackup: 'Restore a backup',
  privacyFootnote: 'Private · stays on this device',
  confirmYou: (name: string) => `We’ll call you ${name}.`,
  workspaceTitle: 'What should we call this space?',
  workspaceNameLabel: 'Workspace name',
  workspaceNameDefault: 'Personal',
  currencyLabel: 'Your currency',
  workspaceHint: 'You can change this later.',
  continue: 'Continue',
  addLater: 'I’ll add this later',
  stageSpace: 'Space',
  stageNow: 'Now',
  stageNext: 'Next',
  stageProtect: 'Protect',
  stageReserve: 'Reserve',
  stageClarity: 'Clarity',
  continueToClarity: 'See my cash clarity',
  reserveHeld: 'We’ll hold this as an everyday buffer.',
  reserveHeldHint: 'It is a guardrail, not a promise that you must spend it.',
  everydayBuffer: 'Everyday buffer',
  removeItem: 'Remove',
  swipeToRemove: 'Swipe a card left to remove it.',
  safeToSpend: 'Safe to spend',
  moneyQuestion: 'What money exists right now?',
  moneyHint: 'Start with the account you use most.',
  accountTypeLabel: 'Account type',
  tapTypeToAdd: 'Tap a type to add it',
  typeBank: 'Bank',
  typeCash: 'Cash',
  typeSavings: 'Savings',
  typeCard: 'Card',
  currentBalance: 'Current balance',
  continueToNext: 'Continue to what comes next',
  addAnotherAccount: 'Add another account',
  addAnotherIncome: 'Add another income',
  addAnotherPayment: 'Add another payment',
  addAnotherBudget: 'Add another boundary',
  moreBudgets: 'What else should have a boundary?',
  savingsSpendableQuestion: 'Is this savings available to spend?',
  savingsSpendable: 'Yes, I can spend it',
  savingsProtected: 'No, keep it protected',
  savingsProtectedShort: 'protected',
  cardOutstanding: 'Outstanding card balance',
  cardPaymentQuestion: 'When do you expect to pay it?',
  cardPaymentAmount: 'Expected payment',
  cardPay: 'Pay',
  cardPaymentReview: (date: string) => `Pay on ${date}`,
  confirmMoneyHave: (amount: string, places: string) => `Got it. ${amount} you have in ${places}.`,
  confirmIncomeNoted: (summary: string) => `Noted, ${summary} hits your accounts.`,
  confirmIncomeHit: (amount: string, name: string, day: string) =>
    `${amount} for ${name} on ${day}`,
  confirmIncomeSkipped: 'No expected income included. Safe to Spend is only cash you have.',
  confirmPaymentMind: (summary: string) => `${summary} — we’ll keep that in mind.`,
  confirmPaymentHit: (amount: string, name: string, day: string) =>
    `${amount} for ${name} on ${day}`,
  confirmBufferTrack: (summary: string) =>
    `We’ll also keep track of ${summary}. That’s estimated everyday spending you can stay under.`,
  confirmBufferMonth: (name: string, amount: string) => `${name}, ${amount} a month`,
  salaryQuestion: 'Do you earn a salary?',
  salaryYes: 'Yes, a regular salary',
  salaryNo: 'No',
  salaryAmount: 'How much do you usually receive?',
  salaryOften: 'How often?',
  monthly: 'Monthly',
  everyTwoWeeks: 'Every 2 weeks',
  weekly: 'Weekly',
  nextDate: 'When is the next one?',
  nextOn: (date: string) => `Next ${date}`,
  nextShort: 'Next',
  dueShort: 'Due',
  dueOn: (date: string) => `Due ${date}`,
  otherIncomeQuestion: 'Do you get money regularly from somewhere else?',
  otherYes: 'Yes',
  notRegularly: 'Not regularly',
  skipForNow: 'Skip for now',
  incomeSource: 'Where does it usually come from?',
  sourceSalary: 'Salary',
  sourceFamily: 'Family',
  sourceRetirement: 'Retirement',
  sourceFreelance: 'Freelance',
  sourceOther: 'Other',
  irregularTitle: 'When do you usually get money?',
  varies: 'It varies',
  notSure: 'I’m not sure',
  irregularHint: 'We won’t guess. Add income later when it becomes clear.',
  protectQuestion: 'What payment would you hate to forget?',
  rent: 'Rent / mortgage',
  subscription: 'Subscription',
  loan: 'Loan / EMI',
  utilities: 'Utilities',
  nothingYet: 'Nothing yet',
  protectAmount: 'How much is it?',
  protectDue: 'When is it due?',
  protectAction: 'Protect this payment',
  reserveQuestion: 'What should have a boundary?',
  reserveHint: 'Start with food, then add other boundaries if you want.',
  reserveCategory: 'Category',
  reserveAmount: 'Monthly amount',
  reserveCustom: 'Custom amount',
  noBudget: 'I don’t want a budget right now',
  foodBoundary: 'Your monthly food boundary',
  setBoundary: 'Set this boundary',
  clarityTitle: 'Here is your cash clarity.',
  overNextDays: (days: number) => `over the next ${days} days`,
  cashYouHave: 'Cash you have',
  expectedIncome: 'Expected income',
  plannedPayment: 'Planned payment',
  foodBuffer: 'Food buffer',
  projectedRoom: 'Projected room',
  clarityHowTitle: 'What you can spend today',
  clarityHeld: 'Held until money arrives',
  clarityHeldNoIncome: 'Already spoken for',
  clarityAheadTitle: 'Still on the way',
  clarityIncomeSubtitle: (date: string) => `Arrives ${date}. Not spendable until then.`,
  clarityIncomeOutside: 'Outside the next 30 days, so it is not counted yet.',
  clarityPaymentAfter: (date: string) => `Due ${date}, after income — paid from that payday.`,
  clarityPaymentBefore: (date: string) => `Due ${date}, before income — held in today’s number.`,
  clarityPaymentOnly: (date: string) => `Due ${date}. Held from cash you have.`,
  clarityBufferSubtitle: 'Monthly boundary. Only the part needed before income is held today.',
  clarityBufferNoIncome: 'Monthly boundary held from cash you have.',
  noIncomeIncluded: 'No expected income included',
  noPaymentIncluded: 'No planned payment reserved',
  noBufferIncluded: 'No everyday buffer included',
  clarityNothingPlanned: 'Nothing is held yet. Safe to Spend is simply the cash you already have.',
  clarityNoCashYet:
    'Add an account when you are ready. This number will follow the cash you actually have.',
  clarityFooter:
    'Safe to Spend is cash you already have, after holding what you will need before money arrives.\n\nProjected room is the same answers added up for after that money lands.\n\nThe total is what you can spend today without worrying about rent, bills, or money you’ve set aside.',
  reviewTitle: 'Your first cash picture',
  reviewIncome: 'Income',
  reviewPayments: 'Payments',
  reviewBuffer: 'Buffer',
  reviewNotAdded: 'Not added yet',
  enterDashboard: 'Enter my dashboard',
  changeSomething: 'Change something',
  finishing: 'Preparing your space…',
  back: 'Back',
  more: 'More options',
  needAccountForPlanned: 'Add a spendable account before we can plan this money.',
} as const;
