export const plannedPaymentFormStrings = {
  formTitleNew: 'New planned payment',
  formTitleEdit: 'Edit planned payment',
  amount: 'Amount',
  namePlaceholder: 'Name, like “Rent”',
  from: 'From',
  to: 'To',
  selectAccount: 'Choose an account',
  selectDestination: 'Choose where it goes',
  searchAccounts: 'Search accounts',
  noMatchingAccounts: 'No matching accounts',
  selected: 'Selected',
  swapAccounts: 'Swap From and To accounts',
  repeats: 'Repeats',
  starts: 'Starts',
  ends: 'Ends',
  never: 'Never',
  recordAutomatically: 'Record automatically',
  automaticDescription: 'Adds the entry on each date',
  note: 'Note',
  addNote: 'Add',
  notePlaceholder: 'Add a note (optional)',
  editNote: 'Edit note',
  saveNote: 'Save note',
  save: 'Save planned payment',
  saving: 'Saving…',
} as const;
