export const plannedPaymentFormStrings = {
  formTitleNew: 'New planned payment',
  formTitleEdit: 'Edit planned payment',
  amount: 'Amount',
  fxAutomatic: 'Estimate at today’s rate. The final conversion is calculated when posted.',
  fxFixed: 'These two amounts repeat unchanged, using your conversion.',
  fxManual: 'Review and edit the conversion each time you post. Automatic recording is off.',
  fxLegacy: 'Existing schedule. Choose a mode to use the From account’s currency.',
  reviewTitle: 'Review payment conversion',
  reviewDescription: 'Changes apply only to this occurrence.',
  postPayment: 'Post payment',
  fxManualRecording: 'Manual FX requires review for each occurrence',
  namePlaceholder: 'Name, like “Rent”',
  from: 'From',
  to: 'To',
  selectAccount: 'Choose an account',
  selectDestination: 'Choose where it goes',
  selected: 'Selected',
  swapAccounts: 'Swap From and To accounts',
  repeats: 'Repeats',
  starts: 'Starts',
  ends: 'Ends',
  never: 'Never',
  recordAutomatically: 'Record automatically',
  automaticDescription: 'Adds the entry on each date',
  note: 'Note',
  addNote: 'Add',
  notePlaceholder: 'Add a note (optional)',
  editNote: 'Edit note',
  saveNote: 'Save note',
  save: 'Save planned payment',
  saving: 'Saving…',
} as const;
