export const plannedDetailRedesignStrings = {
  loadingPreview: 'Loading schedule and activity…',
  missingTitle: 'Planned payment not found',
  goBack: 'Go back',
  nextPayment: 'Next payment',
  missedPayment: 'Missed payment',
  dueToday: 'Due today',
  daysLate: (count: number) => `${count} ${count === 1 ? 'day' : 'days'} late`,
  dueInDays: (count: number) => `Due in ${count} days`,
  inDays: (count: number) => `In ${count} days`,
  pausedSince: (date: string) => `Since ${date}`,
  pausedSinceAround: (date: string) => `Since around ${date}`,
  lastPayment: (month: string) => `Last payment ${month}`,
  ended: 'Ended',
  completedHelp: 'This schedule has ended. Edit its dates to plan more occurrences.',
  paused: 'Paused',
  editedUsually: (amount: string) => `edited, usually ${amount}`,
  from: 'From',
  to: 'To',
  accountUnavailable: 'Account unavailable',
  openAccount: (name: string) => `Open ${name}`,
  recordPayment: 'Record payment',
  skip: 'Skip',
  openPendingEntry: 'Open pending entry',
  comingUp: 'Coming up',
  usualAmount: 'Usual amount',
  comingUpCadence: (cadence: string) => cadence,
  history: 'History',
  details: 'Details',
  seeAll: (count: number) => `See all ${count}`,
  showRecent: 'Show recent',
  loadingHistory: 'Loading history…',
  loadingActivity: 'Loading payment activity…',
  activityUnavailable: 'Could not load payment activity.',
  retryActivity: 'Retry activity',
  paidIn: (count: number) => `paid in ${count} ${count === 1 ? 'payment' : 'payments'}`,
  paidSince: (month: string) => `since ${month}`,
  skipped: 'Skipped',
  reversed: 'Reversed',
  waiting: 'Waiting',
  paid: 'Paid',
  paidAsPlanned: 'Paid as planned',
  paidMore: (amount: string) => `Paid ${amount} more than planned`,
  paidLess: (amount: string) => `Paid ${amount} less than planned`,
  paidDifferentCurrency: (currency: string) => `Paid in ${currency}; planned in another currency`,
  noHistory: 'No occurrences yet.',
  loadEarlier: 'Load earlier entries',
  repeats: 'Repeats',
  recording: 'Recording',
  started: 'Started',
  ends: 'Ends',
  noEndDate: 'No end date',
  note: 'Note',
  manual: 'Manual',
  autoPost: 'Auto-post',
  edit: 'Edit',
  pauseSchedule: 'Pause schedule',
  resumeSchedule: 'Resume schedule',
  resumeExplanation:
    'Resuming restores upcoming occurrences. Occurrences that fell during the pause are skipped.',
  pausedExplanation: 'No payments will be scheduled while this is paused.',
  endedPayments: (count: number) => `paid in ${count} ${count === 1 ? 'payment' : 'payments'}`,
  dueOn: (date: string) => `Was due ${date}`,
  dueTomorrow: 'Due tomorrow',
  paymentDate: (weekday: string, date: string) => `${weekday}, ${date}`,
  dateAndUsualAmount: (date: string, amount: string) => `${date} · edited, usually ${amount}`,
  endCount: (date: string, count: number) => `${date} · ${count} left`,
  nextOccurrenceCadence: (cadence: string) => cadence,
  skippedCount: 'Skipped',
  occurrenceReview: (date: string) => `Review occurrence on ${date}`,
  historyRowLabel: (date: string, status: string, amount: string) =>
    `${date}, ${status}, ${amount}`,
} as const;
