export const plannedListRedesignStrings = {
  summaryTitle: (month: string) => `Still to pay in ${month}`,
  paymentCount: (count: number) => `${count} ${count === 1 ? 'payment' : 'payments'}`,
  otherCurrencies: (count: number) => `+ ${count} in other currencies`,
  comingInCount: (count: number) => `coming in · ${count} ${count === 1 ? 'payment' : 'payments'}`,
  unclassified: (count: number) =>
    `${count} unclassified ${count === 1 ? 'occurrence' : 'occurrences'}`,
  loadError: 'We could not load planned payments.',
  monthStripAccessibility: (month: string, count: number, largestDay?: string) =>
    `${month}: ${count} ${count === 1 ? 'payment' : 'payments'} remaining${largestDay ? `, largest remaining day ${largestDay}` : ''}`,
  monthStripDay: (day: number, outgoing: number, incoming: number) =>
    `Day ${day}: ${outgoing ? 'outgoing payment' : ''}${outgoing && incoming ? ' and ' : ''}${incoming ? 'incoming payment' : ''}`,
  today: 'Today',
  groupOverdue: 'Overdue',
  groupThisWeek: 'This week',
  groupLaterThisMonth: (month: string) => `Later in ${month}`,
  groupNextMonth: (month: string) => month,
  groupLater: 'Later',
  groupPausedEnded: (count: number) => `Paused / Ended · ${count}`,
  daysLate: (days: number) => `${days} ${days === 1 ? 'day' : 'days'} late`,
  record: 'Record',
  autoPost: 'Auto-post',
  dueDateAccessibility: (date: string) => `Due ${date}`,
  recordAccessibility: (name: string, amount: string) => `Record ${name}, ${amount}`,
  recordBusy: 'Recording…',
  recordError: 'Could not record this occurrence. Try again.',
  overdueSchedule: (date: string) => `Due ${date}`,
  paused: 'Paused',
  ended: 'Ended',
  expandPausedEnded: 'Show paused and ended schedules',
  collapsePausedEnded: 'Hide paused and ended schedules',
  rowAccessibilityHint: 'Opens planned payment details',
  incomeRow: 'Income',
  transferRow: 'Transfer',
  outgoingRow: 'Outgoing payment',
  fromTo: (from: string, to: string) => `From ${from} to ${to}`,
  noAccount: 'Unavailable account',
} as const;
