export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

export enum AccountSubtype {
  CASH = 'CASH',
  WALLET = 'WALLET',
  BANK_CHECKING = 'BANK_CHECKING',
  BANK_SAVINGS = 'BANK_SAVINGS',
  FIXED_DEPOSIT = 'FIXED_DEPOSIT',
  MONEY_MARKET = 'MONEY_MARKET',
  BROKERAGE = 'BROKERAGE',
  RETIREMENT = 'RETIREMENT',
  EMERGENCY_FUND = 'EMERGENCY_FUND',
  CREDIT_CARD = 'CREDIT_CARD',
  LINE_OF_CREDIT = 'LINE_OF_CREDIT',
  OVERDRAFT = 'OVERDRAFT',
  MORTGAGE = 'MORTGAGE',
  STUDENT_LOAN = 'STUDENT_LOAN',
  AUTO_LOAN = 'AUTO_LOAN',
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  LOAN = 'LOAN',
  INVESTMENT = 'INVESTMENT',
  RECEIVABLE = 'RECEIVABLE',
  TAX_RECEIVABLE = 'TAX_RECEIVABLE',
  PAYABLE = 'PAYABLE',
  TAX_PAYABLE = 'TAX_PAYABLE',
  OPENING_BALANCE = 'OPENING_BALANCE',
  NET_WORTH_ADJUSTMENT = 'NET_WORTH_ADJUSTMENT',
  TRANSFER_CLEARING = 'TRANSFER_CLEARING',
  SALARY = 'SALARY',
  BUSINESS_INCOME = 'BUSINESS_INCOME',
  INTEREST_INCOME = 'INTEREST_INCOME',
  DIVIDEND_INCOME = 'DIVIDEND_INCOME',
  RENT_INCOME = 'RENT_INCOME',
  FOOD = 'FOOD',
  HOUSING = 'HOUSING',
  TRANSPORT = 'TRANSPORT',
  UTILITIES = 'UTILITIES',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SHOPPING = 'SHOPPING',
  TAX = 'TAX',
  TRANSFER = 'TRANSFER',
  OTHER = 'OTHER',
}

export enum TransactionType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum JournalStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  PLANNED = 'PLANNED',
  SKIPPED = 'SKIPPED',
  PAUSED = 'PAUSED',
}

export enum PlannedPaymentInterval {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum PlannedPaymentStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export type AuditEntityType = 'account' | 'journal' | 'transaction';

export enum InboxProcessingStatus {
  PENDING = 'pending',
  IMPORTED = 'imported',
  AUTO_POSTED = 'auto_posted',
  DISMISSED = 'dismissed',
  DUPLICATE_FLAGGED = 'duplicate_flagged',
  PARSE_FAILED = 'parse_failed',
}

export enum TransactionDirection {
  DEBIT = 'debit',
  CREDIT = 'credit',
  UNKNOWN = 'unknown',
}

export enum JournalDisplayType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  TRANSFER = 'TRANSFER',
  MIXED = 'MIXED',
}

export enum InboxParseStatus {
  PARSED = 'parsed',
  PARSE_FAILED = 'parse_failed',
  IGNORED = 'ignored',
}

export enum SemanticType {
  // Asset sourced
  TRANSFER = 'TRANSFER',
  DEBT_PAYMENT = 'DEBT_PAYMENT',
  OWNER_WITHDRAWAL = 'OWNER_WITHDRAWAL',
  INCOME_REVERSAL = 'INCOME_REVERSAL',
  PURCHASE = 'PURCHASE',

  // Liability sourced
  BORROWING = 'BORROWING',
  LIABILITY_TRANSFER = 'LIABILITY_TRANSFER',
  DEBT_CONVERSION = 'DEBT_CONVERSION',
  LIABILITY_ADJUSTMENT = 'LIABILITY_ADJUSTMENT',
  EXPENSE_ON_CREDIT = 'EXPENSE_ON_CREDIT',

  // Equity sourced
  BALANCE_ADJUSTMENT = 'BALANCE_ADJUSTMENT',
  LIABILITY_FUNDING = 'LIABILITY_FUNDING',
  EQUITY_TRANSFER = 'EQUITY_TRANSFER',
  EQUITY_INCOME_ADJUSTMENT = 'EQUITY_INCOME_ADJUSTMENT',
  OWNER_SPENDING = 'OWNER_SPENDING',

  // Income sourced
  INCOME_RECEIVED = 'INCOME_RECEIVED',
  DEBT_PAYDOWN = 'DEBT_PAYDOWN',
  SAVINGS_ALLOCATION = 'SAVINGS_ALLOCATION',
  INCOME_RECLASSIFICATION = 'INCOME_RECLASSIFICATION',
  TAX_OR_FEE = 'TAX_OR_FEE',

  // Expense sourced
  REFUND = 'REFUND',
  CREDIT_REFUND = 'CREDIT_REFUND',
  EXPENSE_CAPITALIZATION = 'EXPENSE_CAPITALIZATION',
  EXPENSE_REVERSAL = 'EXPENSE_REVERSAL',
  EXPENSE_RECLASSIFICATION = 'EXPENSE_RECLASSIFICATION',

  UNKNOWN = 'UNKNOWN',
}
