export const UI_STRINGS = {
  common: {
    loading: 'Loading…',
    loadingMore: 'Loading…',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    alert: 'Alert',
    confirm: 'Confirm',
    ok: 'OK',
    noTransactions: 'Your financial story starts here.',
    tryChangingFilters: 'No results match these filters',
    allTime: 'All Time',
    searchPlaceholder: 'Search…',
    none: 'None',
  },
  dashboard: {
    emptyTitle: 'Everything is ready.',
    emptySubtitle: 'Add your first entry to see how much you can spend with confidence.',
    recentTransactions: 'Activity',
    searchResults: 'Results',
    greeting: (name: string) => `Hi, ${name || 'there'}`,
    notificationsTitle: 'Notifications',
    safeToSpendTitle: 'Safe to Spend',
    triggeringTransactionsTitle: 'Source Activity',
    dismissedNotificationsTitle: 'Dismissed',
    noDismissedNotifications: 'No dismissed notifications.',
    restore: 'Restore',
    manageDismissed: 'Manage',
    assets: 'Available Now',
    debts: 'Outstanding',
    budgets: 'Reserved',
    bills: 'Bills',
    shortfall: 'Shortfall',
    neededForObligations: 'Reserved',
    afterObligations: 'Remaining',
    insightDetails: {
      title: 'Why This Changed',
      emptyTitle: 'No source activity',
      emptySubtitle: 'The entries behind this item are no longer in your ledger.',
      impact: 'Effect on Safe to Spend',
      whyThisAppeared: 'Reason: ',
      recommendedAction: 'What happens next',
      basisText: (days: number) => `Based on the last ${days} days`,
      severityLabel: {
        high: 'Large effect',
        medium: 'Moderate effect',
        low: 'Small effect',
      },
    },
    noDataForBreakdown:
      'Safe to Spend is below zero, so there is no available balance to break down.',
    safeToSpendExplanation: {
      title: 'How Safe to Spend Is Calculated',
      intro:
        'Safe to Spend is the money left after pending charges, upcoming bills, and other committed amounts are counted.',
      unlocks:
        'The number is conservative. If money may be needed soon, it is not treated as free to spend.',
      formulaTitle: 'Calculation',
      formulaItems: [
        'Available now: cash and cash-like account balances you can use soon.',
        (days: number) =>
          `Incoming: expected pay, refunds, and transfers scheduled within ${days} days.`,
        (days: number) =>
          `Reserved: bills, planned payments, transfers, and budgeted spending expected within ${days} days.`,
        'Outstanding debt: balances you still owe. Only the amount due soon reduces Safe to Spend.',
        'Safe to Spend: what remains after those amounts are counted.',
      ],
      bucketTitle: 'Breakdown',
      exampleTitle: 'Current Breakdown',
      benefitsTitle: 'Why These Amounts Are Separate',
      benefits: [
        'Available money is shown after committed money is removed.',
        'Pending and scheduled items affect the number before they settle.',
        'You can open any amount to see the entries behind it.',
      ],
      footer: 'This calculation depends on account subtypes, planned payments, and budget scopes.',
      closeCta: 'Close',
    },
    legendDetails: {
      safeTitle: 'Safe to Spend',
      safeDesc: (days: number) => `Money left after funds are reserved for the next ${days} days.`,
      committedTitle: 'Reserved',
      committedDesc: (days: number) =>
        `Money set aside for planned payments, transfers, and active budgets in the next ${days} days.`,
      debtsTitle: 'Outstanding',
      debtsDesc: (days: number) =>
        `Balances you still owe. The amount due within ${days} days is already included in Reserved.`,
      inflowTitle: 'Incoming',
      inflowDesc: (days: number) => `Expected income and transfers within ${days} days.`,
    },
    safeToSpendUi: {
      safePrefix: 'Safe to Spend:',
      committedPrefix: 'Reserved:',
      debtsPrefix: 'Outstanding:',
      inflowPrefix: 'Incoming:',
      financiallySecure: 'Available',
      assetsBucket: 'Available Now',
      debtsBucket: 'Outstanding Debt',
      debtsHint: 'Balances you still owe and have not matched to a repayment plan.',
      debtsCallout:
        'The due amount is already included in Reserved because a repayment plan exists.',
      budgetsBucket: 'Budget Reserves',
      categoriesUsed: 'Categories used',
      accountsUsed: 'Accounts used',
      noneDetectedYet: 'None found',
      projectedLiquidity: 'Projected available money (Available Now + Incoming):',
      committedLine: 'Reserved (budgets + planned payments):',
      debtsLine: 'Outstanding debt (no repayment plan):',
      safeToSpendLine: 'Safe to Spend:',
      calculationTitle: 'Calculation',
      calculationFormula: "Lower of today's available money and the lowest projected balance",
      plannedPayments: 'Planned payments',
      plannedJournals: 'Planned transfers',
      activeBudgets: (days: number) => `Budget reserves (${days} days)`,
      breakdownByAccount: 'By account',
      totalCommitted: 'Total reserved',
      creditCardStatements: 'Card statements',
      otherLiquidLiabilities: 'Other near-term liabilities',
      totalBalanceInfo: 'Total balance',
      upcomingIncome: 'Incoming',
      emptyAccounts: 'No accounts in this group',
      noFutureIncome: 'No incoming money is scheduled',
      remainingCashBuffer: 'Remaining buffer',
      unplannedBalance: 'Unreserved balance',
      scheduledCommitment: 'Scheduled amount',
      waitingForIncome: 'Incoming needed',
      calculationLedger: 'Calculation details',
      projectedLabel: 'Projected',
    },
    hub: {
      title: 'Review',
      activeTab: 'Active',
      dismissedTab: 'Dismissed',
      unreadSmsTitle: (count: number) =>
        `${count} SMS ${count === 1 ? 'message needs' : 'messages need'} review`,
      unreadSmsSubtitle: 'These messages may create entries after review.',
      emptyState: 'No active items.',
      noDismissed: 'No dismissed items.',
      restore: 'Restore',
      dismiss: 'Dismiss',
      emergencyFund: {
        title: 'No Emergency Fund Account Found',
        description: 'No asset account is marked as Emergency Fund.',
        highlight: 'An emergency fund is money set aside for unexpected costs.',
        fixTitle: 'If you add one',
        step1: 'Create an asset account.',
        step2: 'Choose the Emergency Fund subtype.',
        step3: 'Transfers into that account stay separate from spending money.',
        actionClose: 'Close',
        actionCreate: 'Create account',
        insight: {
          message: 'No Emergency Fund Account Found',
          description: 'No asset account is marked as Emergency Fund.',
          suggestion: 'This appears because the app could not find an Emergency Fund account.',
        },
      },
      subscriptionAmnesia: {
        message: 'Recurring Charge',
        description: (amount: string, desc: string, acc: string) =>
          `${amount} for "${desc}" in "${acc}" appears repeatedly.`,
        suggestion: 'This appears because similar charges were found more than once.',
      },
      spendingSpike: {
        message: 'Higher-Than-Usual Spending',
        description: (subtype: string, percent: number) =>
          `"${subtype}" is ${percent}% above your usual level.`,
        suggestion: 'This is based on recent activity in the same category.',
      },
    },
    notifications: {
      impact: 'Effect',
      whyThisAppeared: 'Reason: ',
      basedOnLastDays: (days: number) => `Based on the last ${days} days`,
      triggersCount: (count: number) => (count === 1 ? '1 trigger' : `${count} triggers`),
      nextStep: 'Next: ',
      planEmergencyFund: 'Emergency Fund account not found',
    },
  },
  journal: {
    emptyTitle: 'No matching entries',
    emptySubtitle: 'No entries match the current search or date range.',
    transactions: 'Activity',
    plannedPayments: 'Planned payments',
    upcoming: 'Scheduled',
    searchResults: 'Results',
    more: (count: number) => `+${count} more`,
    from: 'From: ',
    to: 'To: ',
    transaction: 'Entry',
    transfer: 'Transfer',
    expense: 'Expense',
    income: 'Income',
    transactionCount: (count: number) => (count === 1 ? '1 entry' : `${count} entries`),
    reconciledUntilHere: (dateText: string) => `Reconciled through ${dateText}`,
    errors: {
      missingExchangeRate: (from: string, to: string) =>
        `No exchange rate from ${from} to ${to} was available, so this transaction was left out of the daily net amount.`,
    },
  },
  reports: {
    title: 'Reports',
    tabs: {
      overview: 'Overview',
      spending: 'Spending',
      wealth: 'Wealth',
    },
    netWorthChange: 'Net Worth Change',
    netWorthHistory: 'Net Worth History',
    totalIncome: 'Income',
    totalExpense: 'Expense',
    incomeVsExpenseTrend: 'Income vs Expense',
    incomeBreakdown: 'Income Breakdown',
    spendingBreakdown: 'Spending Breakdown',
    spendingByAccount: 'Spending by Account',
    spendingByCategory: 'Spending by Category',
    incomeByCategory: 'Income by Category',
    spendingHeatmap: 'Spending Heatmap',
    activityCalendar: 'Activity Calendar',
    dailyMomentum: 'Daily Momentum',
    heatmapSubtitle: 'Intensity of spending across weekdays and hours.',
    noData: 'No data in this period.',
    showLess: 'Less',
    showAll: (count: number) => `All (${count})`,
    assets: 'Assets',
    liabilities: 'Liabilities',
    liabilitiesShort: 'Liabil.',
    incomeShort: 'Inc',
    expenseShort: 'Exp',
    maxLabel: 'Max',
    categoryOther: 'Other',
    chartNoData: 'No data available',
    moneyFlowTitle: 'Money Flow (Sankey)',
    filterByAccounts: 'Filter by Accounts',
    allAccounts: 'All Accounts',
    accountCount: (count: number) => (count === 1 ? '1 Account' : `${count} Accounts`),
    viewDetails: 'View Details',
    today: 'Today',
    sankeyTotalIncome: 'Total Income',
    sankeySurplus: 'Savings/Surplus',
  },
  settings: {
    title: 'Settings',
    sections: {
      personalization: 'Profile & Money Defaults',
      profile: 'Profile',
      forecasting: 'Forecasting',
      moneyDefaults: 'Money Defaults',
      moneySetup: 'Money Setup',
      experience: 'Experience',
      protection: 'Protection',
      ledgerData: 'Ledger Data',
      app: 'App',
      remindersAndAutomation: 'Reminders & Automation',
      privacyAndSecurity: 'Privacy & Security',
      aboutAndSupport: 'About & Support',
      maintenanceAndReset: 'Maintenance & Reset',
      displayOptions: 'Display Options',
      protectFinancialDetails: 'Protect Financial Details',
      preferences: 'Preferences',
      communitySupport: 'Community',
      general: 'General',
      appearance: 'Appearance & Display',
      dataManagement: 'Backup, Sharing & History',
      maintenance: 'Maintenance',
      dangerZone: 'Danger Zone',
    },
    appearance: {
      themeTitle: 'Color Theme',
      themeDesc: 'Set the palette for your interface',
      typographyTitle: 'Typography',
      typographyDesc: 'Heading and body typeface',
      modeTitle: 'Mode',
      deepSpace: {
        label: 'Deep Space',
        desc: 'Mint on obsidian, calm authority',
      },
      ivy: {
        label: 'Ivy',
        desc: 'White with purple, clean precision',
      },
      editorial: {
        label: 'Editorial',
        desc: 'Slate, warm, professional',
      },
      goldObsidian: {
        label: 'Gold Obsidian',
        desc: 'Gold on obsidian, warm elegance',
      },
      serifSans: {
        label: 'Serif & Sans',
        desc: 'Elegant serif with clean sans',
      },
      modernGeometric: {
        label: 'Modern Geometric',
        desc: 'Clean geometric sans-serif',
      },
      classicSerif: {
        label: 'Classic Serif',
        desc: 'Readable serif with versatile sans',
      },
      customize: 'Customize',
      preview: 'Aa',
    },
    privacy: {
      title: 'Privacy Mode',
      description: 'Hide balances across the app',
      on: 'On',
      off: 'Off',
      widgetPrivacyTitle: 'Widget Privacy',
      widgetPrivacyDesc: 'Hide balances on home screen widgets',
      appLockTitle: 'App Lock',
      appLockDesc: 'Require biometric or passcode authentication to open the app',
    },
    advancedMode: {
      title: 'Advanced Mode',
      description: 'Use multi-line journal entries and choose every account directly.',
    },
    stats: {
      title: 'Account Stats',
      description: 'Show monthly income and expense on account cards',
    },
    data: {
      backupRestoreHeader: 'Backup & Restore',
      sharingReviewHeader: 'Sharing & Review',
      exportDesc: 'Export your ledger to a JSON backup file.',
      exportBtn: 'Create Backup',
      exportingTitle: 'Exporting Backup',
      exportingWait: 'Optimizing and compressing data...',
      exportingHint: 'This may take a moment for large ledgers.',
      exportFilenameLabel: 'Filename',
      exportFilenamePlaceholder: 'e.g., my-balance-backup',
      importBtn: 'Restore Backup',
      importDesc: 'Restore your data from a backup file',
      auditDesc: 'See every recorded change to your data.',
      auditBtn: 'Audit Trail',
      shareFormatTitle: 'Default Share Format',
      shareFormatDesc: 'Format used when sharing reports',
      shareFormats: {
        TEXT: 'Text',
        CSV: 'CSV',
        MARKDOWN: 'Markdown',
      },
    },
    maintenance: {
      integrityDesc: 'Check your ledger for balance mismatches and repair what can be repaired.',
      integrityBtn: 'Verify Books',
      integrityTitle: 'Verifying Books',
      integrityWait: 'Checking balances…',
      integrityHint: 'This check runs while the app stays open.',
      seedMockDesc:
        'Create a dedicated workspace populated with realistic mock transactions for testing and screenshots.',
      seedMockBtn: 'Setup Demo Workspace',
      seedMockTitle: 'Setting Up Demo Workspace',
      seedMockWait: 'Populating mock ledger…',
      seedMockHint: 'This will not affect your existing workspaces.',
    },
    danger: {
      cleanupDesc: 'Permanently remove records already marked deleted.',
      cleanupBtn: 'Purge Deleted',
      resetDesc: 'Erase all data. This is irreversible.',
      resetBtn: 'Factory Reset',
    },
    version: (v: string) => `Full Frills Balance v${v}`,
    personalization: {
      yourName: 'Your Name',
      yourNamePlaceholder: 'Enter your name',
      yourNameDesc: 'Used for personalized greetings',
      themeTypographyTitle: 'Theme & Typography',
      themeTypographyDesc: 'Colors, fonts, dark mode',
      smsAutoPostTitle: 'SMS Auto-Post',
      smsAutoPostDesc: 'Rules that turn reviewed SMS messages into entries automatically',
      smsAutomationHeader: 'SMS Automation',
      smsImportTitle: 'SMS Import',
      smsInboxTitle: 'SMS Inbox',
      smsInboxDesc: 'Review pending, processed, duplicate, and failed SMS imports',
      forecastTitle: 'Simulation Horizon',
      forecastDesc:
        'Determines how far into the future your balance is projected to calculate Safe-to-Spend.',
    },
    community: {
      telegramTitle: 'Telegram',
      telegramDesc: 'Updates and discussion',
      playStoreTitle: 'Rate on Play Store',
      playStoreDesc: 'Open app page',
      githubTitle: 'GitHub',
      githubDesc: 'Source code and issues',
    },
    importTitle: 'Import',
    importIntro: 'Choose a backup format to replace the data on this device.',
    importNote: 'Import replaces all data for the active workplace.',
    selectFile: (name: string) => `Select ${name} File`,
    currency: {
      title: 'Default Currency',
      description: 'Used for new accounts and totals',
      selectTitle: 'Select Currency',
    },
    notifications: {
      title: 'Reminders',
      description: 'Reminder to review recent activity so Safe to Spend stays current',
      cadenceLabel: 'Cadence',
      none: 'None',
      daily: 'Daily',
      weekly: 'Weekly',
      reminderTitle: 'Review recent activity',
      reminderBody: 'Record recent entries to keep Safe to Spend current.',
      testTitle: 'Test Reminder',
      testBody: 'This is a test notification from Full Frills Balance.',
    },
  },
  transactionFlow: {
    amount: 'Amount',
    descriptionOptional: 'Description',
    saving: 'Saving…',
    save: (type: string) => `Save ${type.toUpperCase()}`,
    continue: 'Continue',
    chooseDifferentAccounts: 'Change accounts',
    fetchingRate: 'Getting exchange rate…',
    simple: 'Simple',
    advanced: 'Advanced',
    explanationIconAccessibility: 'What is Advanced Mode?',
    headers: {
      edit: 'Edit Entry',
      new: 'New Entry',
      default: 'Journal Entry',
    },
    banners: {
      editing: 'Editing this entry',
    },
    simpleEntry: {
      toCategory: 'To Category',
      fromAccount: 'From Account',
      fromSource: 'From Category',
      toAccount: 'To Account',
      sourceAccount: 'Source Account',
      destinationAccount: 'Destination Account',
      defaultDescriptions: {
        transfer: 'Transfer',
        expense: (name: string) => `Paid for ${name}`,
        income: (name: string) => `Income from ${name}`,
      },
    },
  },
  advancedModeExplanation: {
    title: 'Advanced Mode',
    intro:
      'Simple mode records one account in and one account out. Advanced mode supports journal entries with multiple lines.',
    unlocks: 'The entry saves only when total debits equal total credits.',
    exampleTitle: 'Example',
    exampleScenario: '$50 meal paid with $40 from Bank and $10 from Cash.',
    exampleItems: [
      'Bank - Credit $40 (money leaving the account)',
      'Cash - Credit $10 (money leaving the account)',
      'Food - Debit $50 (the expense recorded in the ledger)',
    ],
    whyBetterTitle: 'Why It Exists',
    benefits: [
      'One entry can affect multiple accounts.',
      'The ledger stays balanced because total debits and credits must match.',
      'Useful for split payments, transfers with fees, and payroll entries.',
    ],
    footer: 'Simple mode covers standard entries. Advanced mode is for multi-line journals.',
  },
  accounts: {
    types: {
      asset: 'Asset',
      liability: 'Liability',
      equity: 'Equity',
      income: 'Income',
      expense: 'Expense',
    },
    selectCurrency: 'Currency',
    form: {
      accountName: 'Account Name',
      accountNamePlaceholder: 'e.g., Bank',
      accountType: 'Type',
      accountSubtype: 'Subtype',
      currentBalance: 'Current Balance',
      initialBalance: 'Initial Balance',
      balancePlaceholder: '0.00',
      parentAccount: 'Parent Account',
      clear: 'Clear',
      payDebtFrom: 'Pay Debt From',
      selectPaymentAccount: 'Select Payment Account',
      currencyLockedTooltip:
        'Currency cannot be changed once an account is created to maintain data integrity.',
    },
    categoryForm: {
      categoryName: 'Category Name',
      categoryNamePlaceholder: 'e.g., Food',
      categoryType: 'Type',
      categorySubtype: 'Subtype',
      parentCategory: 'Parent Category',
      formTitleNew: 'New Category',
      formTitleEdit: 'Edit Category',
      expenseCategoryLabel: 'Expense Category',
      incomeCategoryLabel: 'Income Category',
      saveChanges: 'Save Changes',
      createCategory: 'Create Category',
    },
    sections: {
      assets: 'Assets',
      liabilities: 'Liabilities',
      equity: 'Equity',
      income: 'Income Categories',
      expenses: 'Expense Categories',
      other: 'Other Accounts',
    },
    picker: {
      searchPlaceholder: 'Search accounts...',
      noResults: (query: string) => `No accounts found for "${query}"`,
      noAccountsInCategory: 'No accounts available in this category',
      createAccount: 'Create New Account',
      applySelection: (count: number) => `Apply Selection (${count})`,
    },
    hierarchy: {
      title: 'Hierarchy',
      description: 'Drag accounts to reorder them or place them under a parent account.',
      newParentButton: 'New Parent',
      addChild: 'Add child…',
      modalTitle: 'Hierarchy Builder',
      modalDescription: (accountName: string) => `Structure for "${accountName}"`,
      addChildrenLabel: 'ADD AS CHILDREN:',
      moveParentLabel: 'MOVE UNDER PARENT:',
      hasTransactions: 'Has Activity',
    },
    reconciliation: {
      reconciledLabel: (date: string) => `Reconciled through ${date}`,
      alert: {
        title: 'Reconcile Account',
        message:
          'Reconciliation means matching this account to your bank or card statement. Saving it creates a checkpoint at this balance.',
        successMessage: 'Reconciliation saved.',
        pendingTransactions: (count: number) =>
          `${count} ${count === 1 ? 'entry is' : 'entries are'} still unreconciled since the last checkpoint.`,
        matchingBalance: (balance: string) => `Statement balance: ${balance}`,
        guide: 'If the statement balance matches, confirm below.',
      },
    },
  },
  advancedEntry: {
    createTitle: 'New Journal',
    editTitle: 'Edit Journal',
    dateTime: 'Date & Time',
    description: 'Description',
    descriptionPlaceholder: 'What is this journal entry for?',
    journalLines: 'Journal Lines',
    addLine: '+ Add Line',
    addLineAccessibility: 'Add line',
    lineTitle: (index: number) => `Line ${index}`,
    removeLine: 'Remove',
    selectAccount: 'Account',
    type: 'Type',
    debit: 'Debit',
    credit: 'Credit',
    amountPlaceholder: '0.00',
    notes: 'Notes',
    notesPlaceholder: 'Optional notes',
    exchangeRate: 'Exchange Rate',
    autoFetch: 'Get rate',
    ratePlaceholder: 'e.g., 1.1050',
    rateHelpSame: 'Not needed for the same currency',
    rateHelpConvert: (from: string, to: string) => `${from} to ${to} exchange rate`,
    updating: 'Updating…',
    creating: 'Creating…',
    updateJournal: 'Save Changes',
    createJournal: 'Post Journal',
    editing: 'Editing',
  },
  onboarding: {
    iconPickerTitle: 'Select Icon',
    splash: {
      title: 'See What Is\nActually Available',
      subtitle:
        'Safe to Spend removes pending charges, bills, and committed money from the number you see.',
      inputLabel: 'Your name',
      inputPlaceholder: 'Enter your name',
      btnGetStarted: 'Set up app',
      dividerOr: 'OR',
      btnRestore: 'Restore Backup',
    },
    currency: {
      title: 'Choose Your Currency',
      subtitle: 'This is the main currency for new accounts. You can add others later.',
      searchPlaceholder: 'Search currencies…',
    },
    accounts: {
      title: 'Add Your Accounts',
      subtitle: 'Start with the accounts that hold or owe money.',
      placeholder: 'Add account…',
    },
    categories: {
      title: 'Add Your Categories',
      subtitle: 'Choose the income and expense categories you want to track.',
      placeholder: 'Add category…',
      typeLabels: { income: 'Income', expense: 'Expense' },
    },
    appearance: {
      title: 'Choose Appearance',
      subtitle: 'Set colors and type. You can change them later.',
      themeTitle: 'Theme',
      fontTitle: 'Typography',
      previewLabel: 'Preview',
      previewDesc: 'Safe to Spend example',
    },
    finalize: {
      title: 'Setup Complete',
      subtitle: "Setup complete. You're now ready to see what is actually available.",
      btnFinish: 'Open App',
    },
  },
  journalSummary: {
    title: 'Summary',
    totalDebits: 'Debits:',
    totalCredits: 'Credits:',
    balance: 'Difference:',
    totalAmount: 'Total:',
    balanced: (curr: string) => `Balanced in ${curr}`,
    unbalanced: (curr: string) => `Does not balance in ${curr}`,
  },
  validation: {
    accountNameRequired: 'Enter an account name',
    accountNameTooShort: (min: number) => `Use at least ${min} characters`,
    accountNameTooLong: (max: number) => `Use ${max} characters or fewer`,
    invalidCharacters: 'This name contains characters the app cannot save',
    simpleModeTooManyLines: 'Simple mode supports max 2 lines.',
  },
  audit: {
    logTitle: 'Audit Trail',
    editHistory: 'History',
    emptyLogs: 'No audit records yet',
    viewDetails: 'Details',
    viewCta: 'View',
    revertCta: 'Undo',
    revertConfirmTitle: 'Undo Change?',
    revertConfirmMessage: 'This will attempt to revert the record to its previous state. Continue?',
    revertSuccess: 'Change undone successfully',
    idLabel: (id: string) => `ID: ${id}`,
    typeChanged: '(type changed)',
    transactionsLabel: 'entries:',
    accountPrefix: 'Account ',
    entityLabels: {
      account: 'Account',
      journal: 'Journal',
      transaction: 'Entry',
    } as Record<string, string>,
    tables: ['journals', 'transactions', 'accounts'],
    errors: {
      notFound: (id: string) => `No audit record found for ${id}`,
      loadFailed: 'The audit trail could not be loaded.',
      revertFailed: 'Failed to undo change',
      journalDeleteRevertNotSupported:
        'Restoring deleted journals is not yet supported via audit logs. Please use a backup.',
      revertTypeNotSupported: (type: string) => `Reverting ${type} is not supported yet`,
    },
  },
  formats: {
    date: 'YYYY-MM-DD',
  },
  maintenance: {
    importSuccess: 'Import Complete',
    resetComplete: 'Reset Complete',
    seedMockComplete: 'Demo Workspace Ready',
    importDesc: 'The backup replaced the data stored on this device.',
    resetDesc: 'All data on this device was permanently erased.',
    seedMockDesc: 'A dedicated Demo Workspace has been created with realistic mock data.',
    stats: {
      accounts: 'Accounts',
      journals: 'Journals',
      transactions: 'Entries',
      budgets: 'Budgets',
      auditLogs: 'Audit Logs',
      plannedPayments: 'Planned Payments',
      skippedItems: 'Skipped',
      preImportBackup: 'Safety backup',
    },
    restartNote: 'Restart the app to finish applying this change.',
    restartBtn: 'Restart',
  },
  plannedPayments: {
    title: 'Planned Payments',
    details: {
      screenTitle: 'Planned Payment Details',
      deleteConfirmTitle: 'Delete Planned Payment',
      deleteConfirmMessage: 'This permanently removes this planned payment rule.',
      postNowTitle: 'Post Planned Payment Now',
      skipTitle: 'Skip This Occurrence',
      skipConfirm: 'Skip Occurrence',
    },
    emptyTitle: 'No Planned Payments',
    emptySubtitle: 'Recurring rules you create will appear here.',
    nameLabel: 'Rule Name',
    namePlaceholder: 'e.g., Monthly Rent',
    amountLabel: 'Amount',
    amountPlaceholder: '0.00',
    fromAccountLabel: 'From',
    toAccountLabel: 'To',
    selectAccount: 'Account',
    recurrenceTitle: 'Recurrence',
    intervalLabel: 'Interval',
    autoPostLabel: 'Post Automatically',
    saveLabel: 'Save Rule',
    savingLabel: 'Saving…',
    nextOccurrence: (date: string) => `Next occurrence: ${date}`,
    everyDay: 'Daily',
    everyWeek: 'Weekly',
    everyMonth: 'Monthly',
    everyYear: 'Yearly',
    everyN: (n: number, type: string) => `Every ${n} ${type}s`,
    statusPaused: 'Paused',
    formTitleNew: 'New Rule',
    formTitleEdit: 'Edit Rule',
    dayOfWeek: 'Day of Week',
    dayOfMonth: 'Day of Month (1-31)',
    month: 'Month',
    selectMonth: 'Month',
    monthNames: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
    dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  budget: {
    details: {
      deleteTitle: 'Delete Budget',
      deleteConfirm: 'This permanently removes this budget.',
    },
    formTitleNew: 'New Budget',
    formTitleEdit: 'Edit Budget',
  },
  alerts: {
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    validationError: 'Validation Error',
    databaseError: 'Database Error',
    connectionError: 'Connection Error',
    genericError: 'The request did not finish, so nothing was changed.',
    databaseErrorMessage: 'The change could not be saved to local storage.',
    networkErrorMessage: 'The app could not reach the network.',
  },
};
