/** UI copy catalog. Prefer adding new domains as `copy/domains/<name>Strings.ts` re-exported here when a section grows past ~200 lines. */
export const UI_STRINGS = {
  common: {
    loading: 'Loading…',
    loadingMore: 'Loading…',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    alert: 'Alert',
    confirm: 'Confirm',
    ok: 'OK',
    noTransactions: 'A fresh start. Add your first coffee, grocery run, or paycheck.',
    tryChangingFilters: 'No entries match these filters',
    allTime: 'All Time',
    searchPlaceholder: 'Search…',
    none: 'None',
  },
  update: {
    checking: 'Checking for updates…',
    requiredTitle: 'Update required',
    requiredSubtitle:
      'This version of Full Frills is no longer supported. Update the app to keep using your books.',
    availableMessage: 'A newer version of Full Frills Balance is available.',
    updateNow: 'Update now',
    retry: 'Check again',
    unavailable: 'We could not open the app store. Check your connection and try again.',
    exportBackup: 'Export a backup first',
    exportingBackup: 'Preparing backup…',
    exportHint: 'Want to leave instead? Save a backup of all your workplaces before updating.',
    exportFailed: 'Could not create the backup. Try again.',
    viewChangelog: "See what's new",
    changelogTitle: "What's new",
    exportScopeTitle: 'Backup scope',
    exportScopeActive: 'This workplace',
    exportScopeAll: 'All workplaces',
    exportScopeSelected: 'Choose workplaces',
    exportScopeSelectedCount: (count: number) =>
      `${count} workplace${count === 1 ? '' : 's'} selected`,
  },
  dashboard: {
    emptyTitle: 'A fresh start',
    emptySubtitle: 'Record a coffee, bill, or paycheck to see your balance come alive.',
    recentJournalEntries: 'Activity',
    searchResults: 'Results',
    greeting: (name: string) => (name ? `Hi, ${name}` : 'Welcome back'),
    notificationsTitle: 'Notifications',
    safeToSpendTitle: 'Safe to Spend',
    triggeringTransactionsTitle: 'Source Activity',
    dismissedNotificationsTitle: 'Dismissed',
    noDismissedNotifications: 'No dismissed notifications.',
    restore: 'Restore',
    manageDismissed: 'Manage',
    assets: 'Cash in Hand & Bank',
    debts: 'Upcoming Bills & Cards',
    budgets: 'Money Set Aside',
    bills: 'Bills',
    shortfall: 'Holding Back for Bills',
    shortfallSubtitle:
      'Upcoming bills outpace cash right now. Your accounts are fine, but spending money is on hold so you glide smoothly into payday.',
    neededForObligations: 'Set aside',
    afterObligations: 'Guilt-free to spend',
    insightDetails: {
      title: 'Behind This Number',
      emptyTitle: 'No activity found',
      emptySubtitle: 'The entries behind this note are no longer in your records.',
      impact: 'Effect on Safe to Spend',
      whyThisAppeared: 'Why: ',
      recommendedAction: 'What to do next',
      basisText: (days: number) => `Based on your last ${days} days`,
      severityLabel: {
        high: 'Big impact',
        medium: 'Moderate impact',
        low: 'Small impact',
      },
    },
    noDataForBreakdown:
      'Spending money is on hold to protect upcoming bills, so there is no extra cushion right now. Tap info to see how upcoming bills are counted.',
    safeToSpendExplanation: {
      title: 'How Safe to Spend Works',
      intro:
        'Safe to Spend is what you can spend today without worrying about rent, bills, or money you’ve set aside.',
      unlocks:
        'The number is cautious on purpose. If money is spoken for soon, it won’t show up as free to spend. Even if your bank balance looks high, upcoming bills are quietly protected.',
      formulaTitle: 'How it adds up',
      formulaItems: [
        'Cash you have: money in your everyday checking and wallet.',
        (days: number) =>
          `Money coming in: expected paychecks and deposits in the next ${days} days.`,
        (days: number) =>
          `Money set aside: bills, rent, subscriptions, and budgets over the next ${days} days.`,
        'Card balances: money owed soon that is already protected in your reserves.',
        'Safe to Spend: what’s left over to spend completely guilt-free.',
      ],
      bucketTitle: 'The Breakdown',
      exampleTitle: 'Current Picture',
      benefitsTitle: 'Why it keeps you safe',
      benefits: [
        'You see what is truly free to spend after commitments are handled.',
        'Upcoming bills protect your cash before they actually leave your bank.',
        'Tap any category to see every single entry behind it.',
      ],
      footer: 'Calculated from your accounts, planned payments, and category budgets.',
      closeCta: 'Got it',
      logicNote:
        'Paychecks arriving before a bill is due will cover it. Cash is only set aside when a bill comes due first.',
    },
    legendDetails: {
      safeTitle: 'Safe to Spend',
      safeDesc: (days: number) => `What you can comfortably spend over the next ${days} days.`,
      committedTitle: 'Money Set Aside',
      committedDesc: (days: number) =>
        `Money reserved for bills, upcoming payments, and category budgets in the next ${days} days.`,
      debtsTitle: 'Bills & Card Balances',
      debtsDesc: (days: number) =>
        `Balances you owe soon. The amount due in the next ${days} days is already protected in your reserves.`,
      inflowTitle: 'Money Coming In',
      inflowDesc: (days: number) => `Expected paychecks and deposits within ${days} days.`,
    },
    safeToSpendUi: {
      safePrefix: 'Safe to Spend:',
      committedPrefix: 'Reserved:',
      debtsPrefix: 'Upcoming:',
      inflowPrefix: 'Incoming:',
      financiallySecure: 'Available',
      assetsBucket: 'Cash in Hand & Bank',
      debtsBucket: 'Upcoming Bills & Cards',
      debtsHint: 'Balances you still owe and have not matched to a repayment plan.',
      debtsCallout: 'The due amount is already protected in your reserves.',
      budgetsBucket: 'Budget Reserves',
      categoriesUsed: 'Categories used',
      accountsUsed: 'Accounts used',
      noneDetectedYet: 'None found',
      projectedLiquidity: 'Available cash + incoming money:',
      committedLine: 'Money set aside (budgets + bills):',
      debtsLine: 'Card balances & loans:',
      safeToSpendLine: 'Safe to Spend:',
      calculationTitle: 'How it adds up',
      calculationFormula: "Today's cash vs lowest projected balance before next payday",
      plannedPayments: 'Upcoming bills',
      plannedJournals: 'Planned transfers',
      activeBudgets: (days: number) => `Budget reserves (${days} days)`,
      breakdownByAccount: 'By account',
      totalCommitted: 'Total set aside',
      creditCardStatements: 'Card statements',
      otherLiquidLiabilities: 'Other upcoming payments',
      totalBalanceInfo: 'Total balance',
      upcomingIncome: 'Money coming in',
      emptyAccounts: 'No accounts in this group',
      noFutureIncome: 'No upcoming money scheduled',
      remainingCashBuffer: 'Safety cushion',
      unplannedBalance: 'Free to spend',
      scheduledCommitment: 'Scheduled amount',
      waitingForIncome: 'Waiting on payday',
      calculationLedger: 'Calculation details',
      projectedLabel: 'Projected',
    },
    hub: {
      title: 'Review',
      activeTab: 'Active',
      dismissedTab: 'Dismissed',
      unreadSmsTitle: (count: number) =>
        `${count} receipt${count === 1 ? ' needs' : 's need'} review`,
      unreadSmsSubtitle: 'Review and add them to your balance.',
      emptyState: 'All caught up. Everything is in order.',
      noDismissed: 'No dismissed items.',
      restore: 'Restore',
      dismiss: 'Dismiss',
      emergencyFund: {
        title: 'No Rainy-Day Cushion Set Up',
        description: 'You don’t have an account marked as an Emergency Fund.',
        highlight: 'A rainy-day cushion protects your daily spending from unexpected surprises.',
        fixTitle: 'How to set one up',
        step1: 'Add a savings account.',
        step2: 'Choose the Emergency Fund subtype.',
        step3: 'Money in that account stays separate from your everyday spending.',
        actionClose: 'Close',
        actionCreate: 'Add account',
        insight: {
          message: 'No Rainy-Day Cushion Set Up',
          description: 'You don’t have an account marked as an Emergency Fund.',
          suggestion:
            'A separate emergency pot keeps unexpected costs from derailing your daily spending.',
        },
      },
      subscriptionAmnesia: {
        message: 'Did you forget this subscription?',
        description: (desc: string, acc: string) =>
          `"${desc}" in "${acc}" keeps charging you regularly.`,
        suggestion: 'Still using this, or time to cancel and save?',
      },
      spendingSpike: {
        message: 'Spending higher than usual',
        description: (subtype: string, percent: number) =>
          `"${subtype}" is running ${percent}% higher than your usual pace.`,
        suggestion: 'Just a friendly heads-up based on your recent spending pace.',
      },
    },
    notifications: {
      impact: 'Effect',
      whyThisAppeared: 'Reason: ',
      basedOnLastDays: (days: number) => `Based on the last ${days} days`,
      triggersCount: (count: number) => (count === 1 ? '1 trigger' : `${count} triggers`),
      nextStep: 'Next: ',
      planEmergencyFund: 'Emergency Fund account not found',
    },
  },
  journal: {
    emptyTitle: 'Clean slate',
    emptySubtitle: 'No entries match the current search or date range.',
    transactions: 'Activity',
    plannedPayments: 'Planned payments',
    upcoming: 'Scheduled',
    searchResults: 'Results',
    more: (count: number) => `+${count} more`,
    from: 'From: ',
    to: 'To: ',
    transaction: 'Entry',
    transfer: 'Transfer',
    expense: 'Expense',
    income: 'Income',
    transactionCount: (count: number) => (count === 1 ? '1 entry' : `${count} entries`),
    reconciledUntilHere: (dateText: string) => `Reconciled through ${dateText}`,
    errors: {
      missingExchangeRate: (from: string, to: string) =>
        `No exchange rate from ${from} to ${to} was available, so this transaction was left out of the daily net amount.`,
    },
  },
  reports: {
    title: 'Reports',
    tabs: {
      overview: 'Overview',
      spending: 'Spending',
      wealth: 'Wealth',
    },
    netWorthChange: 'Net Worth Change',
    netWorthHistory: 'Net Worth History',
    summaryTitle: 'Period Summary',
    comparedWithPrevious: 'Compared with previous period',
    noPreviousPeriod: 'No previous period to compare',
    summaryHighlights: 'Highlights',
    largestSpendingCategory: 'Largest spending category',
    highestSpendingDay: 'Highest-spend day',
    netFlow: 'Net flow',
    netFlowChange: 'Net flow change',
    viewTransactions: 'View transactions',
    totalIncome: 'Income',
    totalExpense: 'Expense',
    incomeBreakdown: 'Income Breakdown',
    spendingBreakdown: 'Spending Breakdown',
    spendingByAccount: 'Spending by Account',
    spendingByCategory: 'Spending by Category',
    incomeByCategory: 'Income by Category',
    spendingHeatmap: 'Spending Heatmap',
    activityCalendar: 'Activity Calendar',
    dailyMomentum: 'Daily Momentum',
    heatmapSubtitle: 'When you tend to spend throughout the week.',
    noData: 'No activity in this period.',
    showLess: 'Less',
    showAll: (count: number) => `All (${count})`,
    assets: 'Assets',
    liabilities: 'Liabilities',
    liabilitiesShort: 'Liabil.',
    incomeShort: 'Inc',
    expenseShort: 'Exp',
    maxLabel: 'Max',
    categoryOther: 'Other',
    chartNoData: 'No activity to show yet',
    moneyFlowTitle: 'Where Your Money Goes',
    filtersTitle: 'Report filters',
    filtersSubtitle: 'Choose the date range and accounts for this report.',
    applyFilters: 'Apply Filters',
    dateFilter: 'Date',
    filterByAccounts: 'Filter by Accounts',
    allAccounts: 'All Accounts',
    accountCount: (count: number) => (count === 1 ? '1 Account' : `${count} Accounts`),
    viewDetails: 'View Details',
    today: 'Today',
    sankeyTotalIncome: 'Total Income',
    sankeySurplus: 'Saved / Left Over',
    sankeyDrawdown: 'Drawn from Savings',
    sankeyIncomeColumn: 'Income',
    sankeySpendingColumn: 'Spending',
    sankeyIncomeLabel: (name: string) => `Income · ${name}`,
    sankeyExpenseLabel: (name: string) => `Spent · ${name}`,
  },
  reportsV2: {
    title: 'Money overview',
    fetchMissingRates: 'Fetch missing rates',
    fetchMissingRatesTitle: 'Look up historical rates?',
    fetchMissingRatesMessage:
      'We will try to fetch historical rates for the omitted journals, then refresh this report. Posted amounts stay as they are.',
    fetchMissingRatesConfirm: 'Fetch rates',
    fetchMissingRatesNone: 'Nothing needed a rate lookup.',
    fetchMissingRatesUnavailable: 'No historical rates were available for these journals.',
    fetchMissingRatesPartial: (fetched: number, failed: number) =>
      `Found ${fetched} rate${fetched === 1 ? '' : 's'}. ${failed} still unavailable.`,
    fetchMissingRatesSuccess: (fetched: number) =>
      `Found rates for ${fetched} currency date${fetched === 1 ? '' : 's'}. Refreshing the report.`,
    fetchMissingRatesFailed: 'Could not fetch historical rates. Try again when you are online.',
  },
  settings: {
    title: 'Settings',
    workplacePicker: {
      title: 'Choose a workplace',
      subtitle: 'Select which books to open.',
      open: (name: string) => `Open ${name}`,
      create: 'Create workplace',
      import: 'Import workplace',
      opening: 'Opening workplace…',
      switching: 'Switching workplace…',
      loadError: 'Could not load your workplaces',
      loadErrorSubtitle: 'Try again.',
      retry: 'Retry',
    },
    workplaceManagement: {
      deleteTitle: 'Delete workplace?',
      deleteMessage: (name: string, isLast: boolean, isActive: boolean) => {
        const details = `This permanently deletes “${name}”, including its accounts, journals, entries, budgets, planned payments, and other Workplace data. This cannot be undone.`;
        if (isLast)
          return `${details} It is your only Workplace, so you will return to Workplace setup.`;
        if (isActive) {
          return `${details} Because it is currently active, you will choose another Workplace after deletion.`;
        }
        return `${details} Your current Workplace and all other Workplaces will remain unchanged.`;
      },
      deleteConfirm: 'Delete workplace',
    },
    sections: {
      personalization: 'Profile & Money Defaults',
      profile: 'Profile',
      documents: 'Documents',
      currentWorkplace: 'Current Workplace',
      devicesAndSessions: 'Devices & Sessions',
      forecasting: 'Forecasting',
      moneyDefaults: 'Money Defaults',
      moneySetup: 'Money Setup',
      experience: 'Experience',
      protection: 'Protection',
      ledgerData: 'Ledger Data',
      app: 'App',
      privacyAndSecurity: 'Privacy & Security',
      aboutAndSupport: 'About & Support',
      maintenanceAndReset: 'Maintenance',
      displayOptions: 'Display Options',
      protectFinancialDetails: 'Protect Financial Details',
      preferences: 'Preferences',
      communitySupport: 'Community',
      general: 'General',
      appearance: 'Appearance',
      dataManagement: 'Data & Backup',
      maintenance: 'Maintenance',
      dangerZone: 'Danger Zone',
    },
    appearance: {
      themeTitle: 'Color Theme',
      themeDesc: 'Set the palette for your interface',
      typographyTitle: 'Typography',
      typographyDesc: 'Heading and body typeface',
      modeTitle: 'Mode',
      hourCycleTitle: 'Time',
      hourCycleDesc: 'How clock hours are shown across the app.',
      hourCycleSystem: 'System',
      hourCycle12: '12-hour',
      hourCycle24: '24-hour',
      hourCycleHintSystem12: 'System(12 hour)',
      hourCycleHintSystem24: 'System(24 hour)',
      hourCycleHint12: '12 Hour',
      hourCycleHint24: '24 Hour',
      deepSpace: {
        label: 'Deep Space',
        desc: 'Mint on obsidian, calm authority',
      },
      ivy: {
        label: 'Ivy',
        desc: 'White with purple, clean precision',
      },
      editorial: {
        label: 'Editorial',
        desc: 'Slate, warm, professional',
      },
      goldObsidian: {
        label: 'Gold Obsidian',
        desc: 'Gold on obsidian, warm elegance',
      },
      serifSans: {
        label: 'Serif & Sans',
        desc: 'Elegant serif with clean sans',
      },
      modernGeometric: {
        label: 'Modern Geometric',
        desc: 'Clean geometric sans-serif',
      },
      classicSerif: {
        label: 'Classic Serif',
        desc: 'Readable serif with versatile sans',
      },
      customize: 'Customize',
      preview: 'Aa',
    },
    accountPicker: {
      title: 'Compact account picker',
      description: 'Show accounts as space-saving pills when choosing an account',
    },
    privacy: {
      title: 'Privacy Mode',
      description: 'Hide balances across the app',
      on: 'On',
      off: 'Off',
      widgetPrivacyTitle: 'Widget Privacy',
      widgetPrivacyDesc: 'Hide balances on home screen widgets',
      appLockTitle: 'App Lock',
      appLockDesc: 'Require biometric or passcode authentication to open the app',
    },
    advancedMode: {
      title: 'Advanced Mode',
      description: 'Use multi-line journal entries and choose every account directly.',
    },
    stats: {
      title: 'Account Stats',
      description: 'Show monthly income and expense on account cards',
    },
    stsChart: {
      title: 'Safe to Spend Chart',
      description: 'Show the projection line chart on the dashboard',
    },
    data: {
      backupRestoreHeader: 'Backup & Restore',
      reviewHeader: 'Review',
      exportDesc: 'Save a complete backup to a file on your phone.',
      exportBtn: 'Create Backup',
      exportingTitle: 'Exporting Backup',
      exportingWait: 'Optimizing and compressing data...',
      exportingHint: 'This may take a moment for large ledgers.',
      exportFilenameLabel: 'Filename',
      exportFilenamePlaceholder: 'e.g., my-balance-backup',
      importBtn: 'Restore Backup',
      importDesc: 'Restore your books from a previously saved file',
      auditDesc: 'A complete record of every edit or addition made to your books.',
      auditBtn: 'Change History',
      shareFormatTitle: 'Default Share Format',
      shareFormatDesc: 'Format used when sharing reports',
      shareFormats: {
        TEXT: 'Text',
        CSV: 'CSV',
        MARKDOWN: 'Markdown',
      },
    },
    maintenance: {
      integrityDesc:
        'Check your books to ensure every entry adds up cleanly, and fix any mismatches.',
      integrityBtn: 'Check & Repair Books',
      integrityTitle: 'Checking Books',
      integrityWait: 'Making sure everything adds up…',
      integrityHint: 'This check runs while the app stays open.',
      seedMockDesc:
        'Explore a sample space with realistic accounts and bills. Leaves your real books untouched.',
      seedMockBtn: 'Try Demo Books',
      seedMockTitle: 'Setting Up Demo Books',
      seedMockWait: 'Setting up sample books…',
      seedMockHint: 'This will not affect your existing workspaces.',
    },
    danger: {
      cleanupDesc: 'Permanently remove records you previously deleted.',
      cleanupBtn: 'Purge Deleted',
      resetDesc: 'Completely erase all books and start fresh. This cannot be undone.',
      resetBtn: 'Factory Reset',
    },
    version: (v: string) => `Full Frills Balance v${v}`,
    personalization: {
      yourName: 'Your Name',
      yourNamePlaceholder: 'Enter your name',
      yourNameDesc: 'Used for personalized greetings',
      themeTypographyTitle: 'Theme & Typography',
      themeTypographyDesc: 'Colors, fonts, dark mode',
      smsAutoPostTitle: 'SMS Auto-Post',
      smsAutoPostDesc: 'Rules that turn reviewed SMS messages into entries automatically',
      smsAutomationHeader: 'SMS Automation',
      smsImportTitle: 'SMS Import',
      smsInboxTitle: 'SMS Inbox',
      smsInboxDesc: 'Review pending, processed, duplicate, and failed SMS imports',
      forecastTitle: 'How Far Ahead to Look',
      forecastDesc:
        'Sets how many days of upcoming bills and paychecks are factored into your Safe to Spend balance.',
    },
    community: {
      telegramTitle: 'Telegram',
      telegramDesc: 'Updates and discussion',
      releaseNotesTitle: 'Release notes',
      releaseNotesDesc: 'See what changed in each update',
      playStoreTitle: 'Rate on Play Store',
      playStoreDesc: 'Open app page',
      githubTitle: 'GitHub',
      githubDesc: 'Source code and issues',
    },
    importTitle: 'Import',
    importIntro: 'Choose a backup format to replace the data on this device.',
    importNote: 'Restore creates a new Workplace. Existing Workplaces are not changed.',
    newWorkplaceImportIntro:
      'Create a new Workplace from this backup. Existing Workplaces will not be changed.',
    newWorkplaceImportNote: 'The restored books will become a new Workplace.',
    selectFile: (name: string) => `Select ${name} File`,
    currency: {
      title: 'Default Currency',
      description: 'Used for new accounts and totals',
      selectTitle: 'Select Currency',
    },
    notifications: {
      title: 'Notifications',
      description: 'Scheduled reminders to review recent activity',
      automationTitle: 'Notifications & Automation',
      automationDescription: 'Reminders, SMS inbox, and auto-post rules',
      cadenceLabel: 'Cadence',
      none: 'None',
      daily: 'Daily',
      weekly: 'Weekly',
      reminderTitle: 'A quick moment for your books',
      reminderBody: 'Add any recent spending to keep your Safe to Spend balance fresh.',
      testTitle: 'Test Reminder',
      testBody: 'This is a test notification from Full Frills Balance.',
    },
  },
  transactionFlow: {
    amount: 'Amount',
    descriptionOptional: 'Description',
    saving: 'Saving…',
    save: (type: string) => `Save ${type}`,
    postJournal: 'Save entry',
    postSplit: 'Save split',
    postBulk: (count: number) => (count === 1 ? 'Save 1 entry' : `Save ${count} entries`),
    bulkSaving: 'Saving entries…',
    continue: 'Continue',
    chooseDifferentAccounts: 'Change accounts',
    fetchingRate: 'Getting exchange rate…',
    simple: 'Simple',
    advanced: 'Advanced',
    modesHelpAccessibility: 'What is Advanced Mode?',
    headers: {
      edit: 'Edit entry',
      new: 'New entry',
      default: 'New entry',
    },
    banners: {
      editing: 'Editing this entry',
    },
    bulkEntryHint:
      "Add multiple entries at once. Each new row copies the previous one's values for fast entry.",
    bulkEntryMaxRows: (max: number) => `Maximum ${max} entries per post.`,
    splitEntry: {
      title: 'Split entry',
      fromAccount: 'From Account',
      totalAmount: 'Total amount',
      categoriesTitle: 'Categories',
      category: 'Category',
      amount: 'Amount',
      amountPlaceholder: '0.00',
      addSplit: 'Add split',
      removeSplit: 'Remove split',
      splitLabel: (n: number) => `Split ${n}`,
      remainingZero: 'Fully allocated',
      remainingPositive: (amount: string) => `${amount} left to allocate`,
      remainingNegative: (amount: string) => `${amount} over allocated`,
      defaultDescription: 'Split expense',
      save: 'Save split',
      validation: {
        missing_source: 'Choose the account money is paid from.',
        invalid_total: 'Enter a total amount greater than zero.',
        too_few_splits: 'Add at least two category splits.',
        missing_split_account: 'Choose a category for each split.',
        invalid_split_amount: 'Each split needs an amount greater than zero.',
        sum_mismatch: 'Split amounts must add up to the total.',
      },
    },
    simpleEntry: {
      toCategory: 'To Category',
      fromAccount: 'From Account',
      fromSource: 'From Category',
      toAccount: 'To Account',
      sourceAccount: 'Source Account',
      destinationAccount: 'Destination Account',
      chooseAccount: 'Choose account',
      chooseCategory: 'Choose category',
      defaultDescriptions: {
        transfer: 'Transfer',
        expense: (name: string) => `Paid for ${name}`,
        income: (name: string) => `Income from ${name}`,
      },
    },
  },
  journalEntryModesHelp: {
    guided: {
      title: 'Simple',
      body: 'One amount, paid from one account for one purpose. Perfect for daily coffees, groceries, or paychecks.',
    },
    split: {
      title: 'Split',
      body: 'One payment from an account, split across multiple categories. Amounts must add up to the total.',
    },
    advanced: {
      title: 'Advanced',
      body: 'Full double-entry with multiple lines. Saves only when total debits equal total credits.',
    },
    bulk: {
      title: 'Bulk',
      body: 'Several simple entries in one pass. New rows copy the previous row so you can enter a run of transactions quickly.',
    },
  },
  advancedModeExplanation: {
    title: 'Advanced Mode',
    intro:
      'Simple mode records one account in and one account out. Advanced mode lets you build custom multi-line entries.',
    unlocks: 'The entry saves only when total debits equal total credits.',
    exampleTitle: 'Example',
    exampleScenario: '$50 meal paid with $40 from Bank and $10 from Cash.',
    exampleItems: [
      'Bank - Credit $40 (money leaving the account)',
      'Cash - Credit $10 (money leaving the account)',
      'Food - Debit $50 (spending recorded in your books)',
    ],
    whyBetterTitle: 'Why It Exists',
    benefits: [
      'One entry can affect multiple accounts.',
      'Your books stay balanced because total debits and credits must match.',
      'Useful for split payments, transfers with fees, and payroll entries.',
    ],
    footer:
      'Simple mode covers everyday spending. Advanced mode is there whenever you need complete, multi-line flexibility.',
  },
  accounts: {
    emptyTitle: 'No accounts yet',
    emptySubtitle: 'Create your first account to get started.',
    emptyCategoriesTitle: 'No categories yet',
    emptyCategoriesSubtitle: 'Create your first category to get started.',
    types: {
      asset: 'Asset',
      liability: 'Liability',
      equity: 'Equity',
      income: 'Income',
      expense: 'Expense',
    },
    selectCurrency: 'Currency',
    form: {
      accountName: 'Account Name',
      accountNamePlaceholder: 'e.g., Bank',
      accountType: 'Type',
      accountSubtype: 'Subtype',
      currentBalance: 'Current Balance',
      initialBalance: 'Initial Balance',
      balancePlaceholder: '0.00',
      parentAccount: 'Parent Account',
      clear: 'Clear',
      payDebtFrom: 'Pay Debt From',
      selectPaymentAccount: 'Select Payment Account',
      colorPickerTitle: 'Account Color',
      colorAuto: 'Auto (from type)',
      currencyLockedTooltip:
        'To keep past records accurate, an account’s currency can’t be changed once created.',
    },
    balanceClassify: {
      title: 'Classify balance change',
      subtitle: (amountLabel: string) => `How should ${amountLabel} be recorded?`,
      suggested: 'Suggested',
      allAccounts: 'All accounts',
      adjustment: 'Balance Correction',
      adjustmentSubtitle:
        'Adjust the number directly to match reality—without creating fake income or spending.',
      emptySuggested: 'No suggested accounts. Try All accounts or Balance Correction.',
      emptyAll: 'No other accounts in this currency.',
      confirmTitle: 'Confirm balance update',
      confirmMessage: (
        transactionLabel: string,
        amountLabel: string,
        editedName: string,
        otherName: string,
      ) =>
        `This will create a ${transactionLabel} of ${amountLabel} between ${editedName} and ${otherName}.`,
      confirmAdjustmentMessage: (amountLabel: string, editedName: string) =>
        `This will create a Balance Adjustment of ${amountLabel} for ${editedName}, posted against Balance Corrections.`,
      confirmPrimary: 'Create transaction',
      confirmBack: 'Back',
      balanceCorrections: 'Balance Corrections',
    },
    categoryForm: {
      categoryName: 'Category Name',
      categoryNamePlaceholder: 'e.g., Food',
      categoryType: 'Type',
      categorySubtype: 'Subtype',
      parentCategory: 'Parent Category',
      formTitleNew: 'New Category',
      formTitleEdit: 'Edit Category',
      expenseCategoryLabel: 'Expense Category',
      incomeCategoryLabel: 'Income Category',
      saveChanges: 'Save Changes',
      createCategory: 'Create Category',
    },
    sections: {
      assets: 'Assets',
      liabilities: 'Liabilities',
      equity: 'Equity',
      income: 'Income Categories',
      expenses: 'Expense Categories',
      other: 'Other Accounts',
    },
    picker: {
      searchPlaceholder: 'Search accounts...',
      noResults: (query: string) => `No accounts found for "${query}"`,
      noAccountsInCategory: 'No accounts available in this category',
      createAccount: 'Create New Account',
      applySelection: (count: number) => `Apply Selection (${count})`,
    },
    archive: {
      showArchived: 'Show archived',
      hideArchived: 'Hide archived',
      archivedAccount: 'Archived account',
      archivedBadge: 'ARCHIVED',
      archiveAccount: 'Archive account',
      unarchiveAccount: 'Unarchive account',
      archivedSuccess: (name: string) => `"${name}" archived`,
      unarchivedSuccess: (name: string) => `"${name}" unarchived`,
      archiveFailed: 'Failed to archive account',
      unarchiveFailed: 'Failed to unarchive account',
      archiveDescription:
        'Hide this account from lists and pickers. Balances and history are unchanged.',
      unarchiveDescription:
        'Show this account in lists and pickers again. Balances and history are unchanged.',
      systemAccountTitle: 'Archive system account?',
      systemAccountMessage:
        'This account is used automatically by the app. You can still archive it, but some flows may reference it internally.',
      archiveAnyway: 'Archive anyway',
      parentArchivedTitle: 'Parent is archived',
      parentArchivedMessage: (parentName: string) =>
        `"${parentName}" is archived. Unarchive the parent and choose related accounts?`,
      unarchiveParent: 'Unarchive parent',
      thisAccountOnly: 'This account only',
      cascadeArchiveTitle: 'Archive accounts',
      cascadeUnarchiveTitle: 'Unarchive accounts',
      cascadeArchiveDescription: 'Select which accounts to archive.',
      cascadeUnarchiveDescription: 'Select which accounts to unarchive.',
      reorderShowArchivedHint:
        'Use the archive icon in the header to include hidden archived accounts in the sequence.',
    },
    hierarchy: {
      title: 'Organize Accounts',
      description: 'Group accounts together and drag to reorder them.',
      newParentButton: 'New Group',
      addChild: 'Add to group…',
      modalTitle: 'Account Grouping',
      modalDescription: (accountName: string) => `Organization for "${accountName}"`,
      addChildrenLabel: 'GROUP UNDER THIS ACCOUNT:',
      moveParentLabel: 'MOVE INTO GROUP:',
      hasTransactions: 'Has Entries',
    },
    reconciliation: {
      reconciledLabel: (date: string) => `Matched through ${date}`,
      alert: {
        title: 'Match with Bank Statement',
        message:
          'Compare this account with your bank or card statement to confirm your numbers match reality up to this date.',
        successMessage: 'Statement match saved.',
        pendingTransactions: (count: number) =>
          `${count} ${count === 1 ? 'entry is' : 'entries are'} new since your last check.`,
        matchingBalance: (balance: string) => `Statement balance: ${balance}`,
        guide: 'If this matches your statement, confirm below.',
      },
    },
  },
  advancedEntry: {
    createTitle: 'New Entry',
    editTitle: 'Edit Entry',
    dateTime: 'Date & Time',
    description: 'Description',
    descriptionPlaceholder: 'What is this entry for?',
    journalLines: 'Entry Lines',
    addLine: '+ Add Line',
    addLineAccessibility: 'Add line',
    lineTitle: (index: number) => `Line ${index}`,
    removeLine: 'Remove',
    selectAccount: 'Account',
    type: 'Type',
    debit: 'Debit',
    credit: 'Credit',
    amountPlaceholder: '0.00',
    notes: 'Notes',
    notesPlaceholder: 'Optional notes',
    exchangeRate: 'Exchange Rate',
    autoFetch: 'Get rate',
    ratePlaceholder: 'e.g., 1.1050',
    rateHelpSame: 'Not needed for the same currency',
    rateHelpConvert: (from: string, to: string) => `${from} to ${to} exchange rate`,
    updating: 'Updating…',
    creating: 'Creating…',
    updateJournal: 'Save Changes',
    createJournal: 'Save entry',
    editing: 'Editing',
  },
  onboarding: {
    iconPickerTitle: 'Select Icon',
    splash: {
      eyebrow: 'A calmer way to track money',
      title: 'Know what you can actually spend.',
      subtitle:
        'Your bank balance doesn’t know about next week’s bills. We do the quiet math so you always know what’s safe today.',
      inputLabel: 'What should we call you?',
      inputPlaceholder: 'Your name or nickname',
      btnGetStarted: 'Get started',
      dividerOr: 'OR',
      restorePrompt: 'Already have your data?',
      btnRestore: 'Restore from backup',
    },
    currency: {
      title: 'Choose your main currency',
      subtitle: 'This is the default for your accounts. You can add other currencies anytime.',
      searchPlaceholder: 'Search currencies…',
      emptySearch: 'No currencies match that search.',
    },
    accounts: {
      title: 'Where is your money today?',
      subtitle: 'Pick the accounts you use every day. You can add cards and loans later.',
      placeholder: 'Add account…',
      typeLabels: { asset: 'Asset', liability: 'Liability' },
    },
    categories: {
      title: 'What do you spend on?',
      subtitle: 'Choose the everyday categories you want to keep an eye on.',
      placeholder: 'Add category…',
      typeLabels: { income: 'Income', expense: 'Expense' },
    },
    appearance: {
      title: 'Choose your style',
      subtitle: 'Pick colors and fonts that feel good to look at. You can change them anytime.',
      themeTitle: 'Theme',
      fontTitle: 'Typography',
      previewLabel: 'Preview',
      previewDesc: 'Safe to Spend example',
      reviewButton: 'Review choices',
      nextStep: 'Your choices are saved. Take a quick look before stepping in.',
    },
    review: {
      title: 'Ready when you are',
      subtitle: 'Take a quick look below. You can change anything anytime.',
      profile: 'Profile',
      workplace: 'Workplace',
      currency: 'Currency',
      accounts: 'Accounts',
      categories: 'Categories',
      appearance: 'Appearance',
      change: 'Change',
      confirm: 'Step into your books',
      confirming: 'Preparing your space…',
    },
    finalize: {
      title: 'All set',
      subtitle: 'Your quiet space for money is ready.',
      btnFinish: 'See my balance',
    },
  },
  journalSummary: {
    title: 'Summary',
    totalDebits: 'Debits:',
    totalCredits: 'Credits:',
    balance: 'Difference:',
    totalAmount: 'Total:',
    balanced: (curr: string) => `Balanced in ${curr}`,
    unbalanced: (curr: string) => `Does not balance in ${curr}`,
  },
  validation: {
    accountNameRequired: 'Enter an account name',
    accountNameTooShort: (min: number) => `Use at least ${min} characters`,
    accountNameTooLong: (max: number) => `Use ${max} characters or fewer`,
    invalidCharacters: 'This name contains characters the app cannot save',
    simpleModeTooManyLines: 'Simple mode supports max 2 lines.',
  },
  audit: {
    logTitle: 'Change History',
    editHistory: 'History',
    emptyLogs: 'No recorded changes yet',
    viewDetails: 'Details',
    viewCta: 'View',
    revertCta: 'Undo',
    revertConfirmTitle: 'Undo Change?',
    revertConfirmMessage: 'This will attempt to revert the record to its previous state. Continue?',
    revertSuccess: 'Change undone successfully',
    idLabel: (id: string) => `ID: ${id}`,
    typeChanged: '(type changed)',
    transactionsLabel: 'entries:',
    accountPrefix: 'Account ',
    entityLabels: {
      account: 'Account',
      journal: 'Journal',
      transaction: 'Entry',
    } as Record<string, string>,
    tables: ['journals', 'transactions', 'accounts'],
    errors: {
      notFound: (id: string) => `No audit record found for ${id}`,
      loadFailed: 'Could not load change history.',
      revertFailed: 'Failed to undo change',
      journalDeleteRevertNotSupported:
        'Restoring deleted journals is not yet supported via audit logs. Please use a backup.',
      revertTypeNotSupported: (type: string) => `Reverting ${type} is not supported yet`,
    },
  },
  formats: {
    date: 'YYYY-MM-DD',
  },
  maintenance: {
    importSuccess: 'Import Complete',
    resetComplete: 'Reset Complete',
    seedMockComplete: 'Demo Workspace Ready',
    importDesc: 'The backup replaced the data stored on this device.',
    resetDesc: 'All data on this device was permanently erased.',
    seedMockDesc: 'A dedicated Demo Workspace has been created with realistic mock data.',
    stats: {
      accounts: 'Accounts',
      journals: 'Journals',
      transactions: 'Entries',
      budgets: 'Budgets',
      auditLogs: 'Audit Logs',
      plannedPayments: 'Planned Payments',
      skippedItems: 'Skipped',
      preImportBackup: 'Safety backup',
    },
    restartNote: 'Restart the app to finish applying this change.',
    restartBtn: 'Restart',
  },
  plannedPayments: {
    title: 'Planned Payments',
    details: {
      screenTitle: 'Planned Payment Details',
      deleteConfirmTitle: 'Delete Planned Payment',
      deleteConfirmMessage: 'This permanently removes this planned payment rule.',
      postNowTitle: 'Post Planned Payment Now',
      skipTitle: 'Skip This Occurrence',
      skipConfirm: 'Skip Occurrence',
    },
    emptyTitle: 'No recurring bills added',
    emptySubtitle:
      'Add rent, subscriptions, and regular bills so Safe to Spend can protect that money in advance.',
    emptyActionLabel: 'Add bill',
    nameLabel: 'Rule Name',
    namePlaceholder: 'e.g., Monthly Rent',
    amountLabel: 'Amount',
    amountPlaceholder: '0.00',
    fromAccountLabel: 'From',
    toAccountLabel: 'To',
    selectAccount: 'Account',
    recurrenceTitle: 'Recurrence',
    intervalLabel: 'Interval',
    autoPostLabel: 'Post Automatically',
    saveLabel: 'Save Rule',
    savingLabel: 'Saving…',
    nextOccurrence: (date: string) => `Next occurrence: ${date}`,
    everyDay: 'Daily',
    everyWeek: 'Weekly',
    everyMonth: 'Monthly',
    everyYear: 'Yearly',
    everyN: (n: number, type: string) => `Every ${n} ${type}s`,
    statusPaused: 'Paused',
    statusActive: 'Active',
    statusOverdue: 'Overdue',
    statusDueSoon: 'Due Soon',
    formTitleNew: 'New Rule',
    formTitleEdit: 'Edit Rule',
    dayOfWeek: 'Day of Week',
    dayOfMonth: 'Day of Month (1-31)',
    month: 'Month',
    selectMonth: 'Month',
    monthNames: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
    dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  budget: {
    emptyTitle: 'No spending limits set',
    emptySubtitle:
      'Give categories you want to keep on a leash—like dining out—a comfortable monthly ceiling.',
    emptyActionLabel: 'Add budget',
    loading: 'Loading budget…',
    activityTitle: 'Activity',
    activityEmptyTitle: 'No activity',
    activityEmptySubtitle: 'No journal entries found for this budget in the selected period.',
    spentLabel: 'Spent',
    remainingLabel: 'Remaining',
    overLimitLabel: 'Over limit',
    backToToday: 'Back to today',
    endsToday: 'Ends today',
    daysLeft: (days: number) => `${days} days left`,
    overLastPeriod: 'Over last period',
    underLastPeriod: 'Under last period',
    statusOnTrack: 'On track',
    statusNearLimit: 'Near limit',
    statusOverBudget: 'Over budget',
    details: {
      screenTitle: 'Budget Details',
      deleteTitle: 'Delete Budget',
      deleteConfirm: 'This permanently removes this budget.',
    },
    formTitleNew: 'New Budget',
    formTitleEdit: 'Edit Budget',
  },
  alerts: {
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    validationError: 'Validation Error',
    databaseError: 'Database Error',
    connectionError: 'Connection Error',
    genericError: 'Something didn’t go as planned. Your balance remains completely unchanged.',
    databaseErrorMessage: 'Could not save this change to your phone’s storage.',
    networkErrorMessage: 'Could not reach the network.',
  },
};
