import { IconName } from '@/src/components/core';
import { PeriodMetrics } from '@/src/features/accounts/hooks/details/useAccountDetailsMetrics';
import { SubAccountViewModel } from '@/src/features/accounts/hooks/details/useAccountHierarchyTree';
import { AccountId, JournalId } from '@/src/types/domain';
import { JournalListItem } from '@/src/types/ui';
import { DateRange, PeriodFilter } from '@/src/utils/dateUtils';

export type { PeriodMetrics, SubAccountViewModel };

export interface AccountDetailsViewModel {
  accountId: AccountId;
  accountLoading: boolean;
  accountMissing: boolean;
  accountName: string;
  accountType: string;
  accountSubtypeLabel: string;
  accountTypeVariant: string;
  accountIcon: IconName | null;
  accountTypeColorKey: string;
  isDeleted: boolean;
  isArchived: boolean;
  currencyCode: string;
  balanceAmount: number | null;
  transactionCountText: string;
  headerActions: {
    canRecover: boolean;
    onRecover: () => void;
    onEdit: () => void;
  };
  onReconcilePress?: () => void;
  isReconcileModalVisible: boolean;
  setIsReconcileModalVisible: (visible: boolean) => void;
  onConfirmReconcile: () => void;
  reconciledAt: Date | null;
  onBack: () => void;
  onAuditPress: () => void;
  onAddPress: () => void;
  dateRange: DateRange | null;
  periodFilter: PeriodFilter;
  isDatePickerVisible: boolean;
  showDatePicker: () => void;
  hideDatePicker: () => void;
  navigatePrevious?: () => void;
  navigateNext?: () => void;
  onDateSelect: (range: DateRange | null, filter: PeriodFilter) => void;
  chartData: { x: number; y: number }[];
  rollingAverageData: { x: number; y: number }[];
  xTicks: number[];
  periodMetrics: PeriodMetrics;
  journalsLoading: boolean;
  journalsLoadingMore: boolean;
  journalItems: JournalListItem[];
  onLoadMore?: () => void;
  secondaryBalances: { currencyCode: string; amount: number }[];
  isParent: boolean;
  subAccountCount: number;
  subAccounts: SubAccountViewModel[];
  subAccountsLoading: boolean;
  isSubAccountsModalVisible: boolean;
  onShowSubAccounts: () => void;
  onHideSubAccounts: () => void;
  unreconciledCount: number;
  unreconciledAmount: number;
  selectedIds: Set<JournalId>;
  isSelectionModeActive: boolean;
  onLongPressItem: (id: JournalId) => void;
  toggleSelection: (id: JournalId) => void;
  selectAll: () => void;
  clearItems: () => void;
  exitSelectionMode: () => void;
  onShareSelected: () => void;
  setSelectedIds: React.Dispatch<React.SetStateAction<Set<JournalId>>>;
}
